import { createContext, useContext, useState, useEffect, useRef, ReactNode } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { apiPatch } from '@/lib/api';

export type Language = 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    'nav.dashboard': 'Дашборд',
    'nav.products': 'Товары',
    'nav.analytics': 'Аналитика',
    'nav.competitors': 'Конкуренты',
    'nav.trends': 'Тренды',
    'nav.reports': 'Отчёты',
    'nav.support': 'Поддержка',
    'nav.training': 'Обучение',

    // Training (video playlist)
    'learning.title': 'Обучение',
    'learning.subtitle': 'Видеоуроки по работе с сервисом',
    'learning.back': 'Назад',
    'learning.playlist': 'Уроки',
    'learning.videoLoadError': 'Видео не загрузилось.',
    'learning.videoNoHtml5': 'Ваш браузер не поддерживает тег video.',
    'learning.videoSummary.title': 'Сводка',
    'learning.videoSummary.desc': 'Вкладки сводки, фильтры и блоки метрик',
    'learning.videoByDay.title': 'По дням',
    'learning.videoByDay.desc': 'Динамика продаж и прибыли по дням',
    'learning.videoGoods.title': 'Товары',
    'learning.videoGoods.desc': 'Таблица товаров, карточки и ABC-анализ',
    'learning.videoAdditionalExpenses.title': 'Доп. расходы',
    'learning.videoAdditionalExpenses.desc': 'Учёт расходов сверх стандартных статей',
    'learning.videoShipment.title': 'Отгрузка',
    'learning.videoShipment.desc': 'Расчёт рекомендуемого количества к отгрузке',
    'learning.videoMonthly.title': 'Помесячно',
    'learning.videoMonthly.desc': 'Помесячная аналитика продаж и прибыли',

    // Tabs
    'tabs.summary': 'Сводка',
    'tabs.products': 'Товары',
    'tabs.daily': 'По дням',
    'tabs.expenses': 'Расходы',
    'tabs.shipment': 'Поставка',
    'tabs.services': 'Услуги',

    // Uzum API services tab
    'services.title': 'Подключение UZUM Seller API',
    'services.description': 'Вставьте ключ для интеграции из личного кабинета Uzum в разделе: Настройки → API ключи',
    'services.descriptionInstruction': 'Как это сделать? (Инструкция)',
    'services.instructionTitle': 'Вставьте ключ для интеграции из личного кабинета Uzum:',
    'services.instructionStep1Prefix': 'Зайдите в личный кабинет Uzum → ',
    'services.instructionStep1Link': 'Настройки → API ключи',
    'services.instructionStep1Suffix': '.',
    'services.instructionStep2': 'Создайте ключ.',
    'services.instructionStep2GuideLink': 'Подключение за 3 шага',
    'services.instructionStep3': 'Скопируйте ключ в окно подключения в сервисе PROFiboard.',
    'services.instructionImportant': 'ВАЖНО: Подключение займет от 4 до 10 минут.',
    'services.descriptionOpenApi': 'Исследуйте официальный OpenAPI продавца Uzum Market. Ключ создаётся в личном кабинете seller.uzum.uz.',
    'services.apiKeyHintSaved': 'Ключ сохраняется в вашем аккаунте. Чтобы сменить — введите новый и нажмите «Подключить».',
    'services.apiKeyBearerHint': 'Вставляйте только сам токен, без слова Bearer — Uzum принимает Authorization: <токен>.',
    'services.apiKeyLabel': 'API-ключ Uzum',
    'services.apiKeyPlaceholder': 'Вставьте ключ из кабинета продавца',
    'services.apiKeyHint': 'Подключение займет от 4 до 10 минут.',
    'services.keyInvalid': 'Ключ не принят Uzum API',
    'services.keyInvalidUserMessage': 'Некорректный ключ. Вставьте ключ или свяжитесь с поддержкой',
    'services.keyInsufficientAccessUserMessage': 'Ключ принят, но недостаточно прав для выгрузки данных. При создании ключа в Uzum Seller выберите нужные магазины и доступ к заказам, финансам и товарам. Свяжитесь с поддержкой, если ошибка повторяется.',
    'services.shopUnavailableUserMessage': 'Ключ принят, но магазин недоступен для API. Проверьте статус магазина в кабинете Uzum Seller или используйте ключ другого аккаунта.',
    'services.keyWarningTitle': 'Проверьте API-ключ',
    'services.apiKeyRequired': 'Укажите API-ключ',
    'services.connect': 'Подключить',
    'services.connectInProgress': 'Загрузка данных…',
    'services.connectStepApi': 'Подключаем API…',
    'services.connectStepSales': 'Анализируем продажи…',
    'services.connectStepProfit': 'Считаем прибыль…',
    'services.connectStepDashboard': 'Строим dashboard…',
    'services.connectFailed': 'Не удалось подключиться к Uzum API',
    'services.noSavedApiKey': 'Сначала подключите API — сохранённый ключ не найден',
    'services.refreshFailed': 'Не удалось получить сохранённый API-ключ',
    'services.swaggerLink': 'Документация Swagger Uzum',
    'services.errorTitle': 'Ошибка',
    'services.endpointsTitle': 'Доступные методы API',
    'services.endpointsCount': 'эндпоинтов',
    'services.responseTitle': 'Ответ API',
    'services.responseHint': 'Нажмите ▶ у метода, чтобы выполнить GET-запрос и посмотреть данные',
    'services.pickEndpoint': 'Выберите метод слева и нажмите ▶',
    'services.loading': 'Запрос к Uzum…',
    'services.tryRequest': 'Выполнить запрос',
    'services.untagged': 'Без категории',
    'services.exportTitle': 'Выгрузка отчётов для загрузки в сервис',
    'services.exportDescription': 'Файлы в формате XLSX, как при ручной загрузке (sells-report, expenses-report и др.). Данные берутся из Uzum Seller API.',
    'services.exportBoldHint': 'Колонки, которых нет в API, выделены жирным в Excel и в предпросмотре — ячейки будут пустыми.',
    'services.exportFailed': 'Не удалось выгрузить файл',
    'services.previewFailed': 'Не удалось загрузить предпросмотр',
    'services.preview': 'Просмотр',
    'services.previewTitle': 'Предпросмотр',
    'services.previewShown': 'показано',
    'services.rows': 'строк',
    'services.noRows': 'Нет данных за выбранный период',
    'services.columnsFromApi': 'колонок из API',
    'services.dateFrom': 'с',
    'services.dateTo': 'по',
    'services.skippedShops': 'Часть магазинов пропущена — для них нет доступа в финансовом API Uzum.',
    'services.rateLimit': 'Uzum временно ограничил частоту запросов. Подождите 1–2 минуты и повторите.',
    'services.loadData': 'Загрузить данные',
    'services.loadDataInProgress': 'Загрузка данных…',
    'services.loadDataHint': 'Выгружает 4 отчёта из Uzum API с начала года и импортирует их в сервис.',
    'services.loadDataSuccess': 'Данные загружены',
    'services.syncRequestInterrupted': 'Не удалось завершить запрос. Если загрузка уже началась, она может продолжаться на сервере. Проверьте статус через несколько минут.',
    'services.loadDataFailed': 'Не удалось загрузить данные',

    // Help → Подключить API (отдельная копия окна из архива)
    'helpConnectApi.heroTitle': 'Подключение API за 3 шага',
    'helpConnectApi.watchVideo': 'Смотреть видео (~2 мин)',
    'helpConnectApi.benefitsHeading': 'Что вы получите после загрузки',
    'helpConnectApi.benefit1Title': 'Прибыль и реальные',
    'helpConnectApi.benefit1Desc': 'показатели по дням',
    'helpConnectApi.benefit2Title': 'Топ прибыльные',
    'helpConnectApi.benefit2Desc': 'и убыточные товары',
    'helpConnectApi.benefit3Title': 'Все расходы',
    'helpConnectApi.benefit3Desc': 'и комиссии Uzum',
    'helpConnectApi.benefit4Title': 'Остатки и хранение',
    'helpConnectApi.benefit4Desc': 'товаров',
    'helpConnectApi.benefit5Title': 'Тренды и динамика',
    'helpConnectApi.benefit5Desc': 'продаж',
    'helpConnectApi.dataSafetyTitle': 'Ваши данные в безопасности',
    'helpConnectApi.dataSafetyBody':
      'Мы не передаем данные третьим лицам. Вы можете удалить их в любой момент.',
    'helpConnectApi.step1Title': 'Подключение UZUM Seller API',
    'helpConnectApi.step1Line2': '2. Создайте ключ.',
    'helpConnectApi.step1Line3': '3. Скопируйте ключ в окно подключения в сервисе PROFiboard.',
    'helpConnectApi.step1Footnote': 'Подключение займет от 4 до 10 минут.',
    'helpConnectApi.whileConnectingText':
      '✨ Уже через несколько минут вы сможете видеть аналитику своего магазина в реальном времени. Пока идет подключение, посмотрите обзор дашборда и узнайте, какие товары приносят прибыль, где растут расходы и на что стоит обратить внимание в первую очередь.',
    'helpConnectApi.dashboardOverviewButton': 'Смотреть обзор дашборда',
    'helpConnectApi.step2Title': 'Загрузите 4 отчета в PROFiboard',
    'helpConnectApi.step2Body':
      '1. Нажмите на кнопку «Загрузить отчеты» в шапке сервиса PROFiboard.\n2. Перетащите файлы или нажмите на окно загрузки.',
    'helpConnectApi.socialProofBold': '98% продавцов',
    'helpConnectApi.socialProofRest':
      'уже получают аналитику через 2 минуты после первой загрузки отчетов',
    'helpConnectApi.demoHeading': 'Не хотите загружать сейчас?',
    'helpConnectApi.demoSubtitle': 'Посмотрите демо-дашборд с примерами реальных данных.',
    'helpConnectApi.demoButton': 'Посмотреть демо',
    'helpConnectApi.demoPreviewAlt': 'Превью демо-дашборда PROFiboard',
    'helpConnectApi.telegramHelpTitle': 'Нужна помощь с подключением?',
    'helpConnectApi.telegramHelpBody':
      'Ответим в течение 5 минут в Telegram и поможем шаг за шагом.',

    // Filters
    'filter.today': 'Сегодня',
    'filter.yesterday': 'Вчера',
    'filter.week': 'Неделя',
    'filter.month': 'Месяц',
    'filter.year': 'Год',
    'filter.period': 'Период',
    'filter.all': 'Все',
    'filter.excess': 'Избыток',
    'filter.outOfStock': 'Нет на складе',
    'filter.needSupply': 'Нужна поставка',
    
    // KPI Cards
    'kpi.revenue': 'Выручка',
    'kpi.orders': 'Заказы',
    'kpi.returns': 'Возвраты',
    'kpi.profit': 'Прибыль',
    'kpi.marginality': 'Маржинальность',
    'kpi.averageCheck': 'Средний чек',
    
    // Blocks
    'block.finances': 'Финансы',
    'block.expenses': 'Расходы',
    'block.warehouse': 'Склад',
    'block.revenueProgress': 'Накопительная выручка',
    
    // Finance items
    'finance.revenue': 'Выручка',
    'finance.logistics': 'Логистика',
    'finance.commission': 'Комиссия',
    'finance.promoDiscount': 'Скидка по акции',
    'finance.netRevenue': 'Чистая выручка',
    
    // Expense items
    'expense.soldGoodsCost': 'Себест. проданных товаров',
    'expense.logistics': 'Логистика',
    'expense.commission': 'Комиссия',
    'expense.promoDiscount': 'Скидка по акции',
    'expense.advertising': 'Реклама',
    'expense.fines': 'Штрафы',
    'expense.storage': 'Хранение',
    'expense.other': 'Прочее',
    'expense.total': 'Итого расходов',
    
    // Warehouse items
    'warehouse.warehouseStock': 'Себест. товара на складе',
    'warehouse.potentialRevenue': 'Потенциальная выручка',
    'warehouse.potentialProfit': 'Потенциальная прибыль',
    
    // Table headers
    'table.product': 'Товар',
    'table.article': 'Артикул',
    'table.category': 'Категория',
    'table.costPrice': 'Себестоимость',
    'table.price': 'Цена',
    'table.orders': 'Заказы',
    'table.returns': 'Возвраты',
    'table.stock': 'Остаток',
    'table.stockFbo': 'Остаток (FBO)',
    'table.stockFbs': 'Остаток (FBS)',
    'table.availability': 'Наличие',
    'table.revenue': 'Выручка',
    'table.profit': 'Прибыль',
    'table.margin': 'Маржа',
    
    // Availability status
    'availability.excess': 'Избыток',
    'availability.outOfStock': 'Нет на складе',
    'availability.needSupply': 'Нужна поставка',
    
    // Header
    'header.search': 'Поиск товаров, категорий...',
    'header.notifications': 'Уведомления',
    'header.notificationsTooltip': 'Рейтинг, штрафы и другие удержания маркетплейса.',
    'notification.lowRating': 'Рейтинг товара упал ниже 4.5',
    'notification.openProductCard': 'Открыть карточку товара',
    'header.allNotifications': 'Все уведомления',
    'header.noNotifications': 'Нет уведомлений',
    'header.deleteNotification': 'Удалить уведомление',
    'header.deleteAllNotifications': 'Удалить все',
    'header.help': 'Помощь',
    'header.helpTooltip': 'Справка, обучение и связь с поддержкой',
    'header.helpUploadReports': 'Загрузка отчётов',
    'header.helpConnectApi': 'Подключение API за 3 шага',
    'header.enterCogs': 'Внести себестоимость',
    'header.connectApi': 'Подключить API',
    'header.refreshApi': 'Обновить данные',
    'header.refreshApiTooltip': 'Обновить данные через API Uzum',
    'header.apiConnected': 'API подключён',
    'header.videoTutorials': 'Видео-уроки',
    'header.support': 'Связаться с поддержкой',
    'header.myAccount': 'Мой аккаунт',
    'header.profile': 'Профиль',
    'header.adminPanel': 'Админ-панель',
    'header.tariff': 'Тариф',
    'header.extendTariff': 'Продлить тариф',
    'header.language': 'Язык',
    'header.logout': 'Выйти',

    'support.title': 'Центр поддержки',
    'support.subtitle': 'Ответы по PROFiboard и обращение в поддержку',
    'support.tabHelp': 'Справка',
    'support.tabContact': 'Связаться',
    'support.faqHeading': 'Частые вопросы',
    'support.contactFormTitle': 'Создать обращение',
    'support.viaTelegramHeading': 'Telegram',
    'support.viaTelegramHint': 'Отсканируйте QR-код или нажмите на изображение, чтобы открыть чат.',
    'support.telegramQrAlt': 'QR-код для связи в Telegram',
    'support.fieldSubject': 'Тема',
    'support.fieldSubjectPh': 'Кратко опишите вопрос',
    'support.fieldPriority': 'Приоритет',
    'support.priorityLow': 'Низкий',
    'support.priorityMedium': 'Средний',
    'support.priorityHigh': 'Высокий',
    'support.priorityCritical': 'Критический',
    'support.fieldCategory': 'Категория',
    'support.catTechnical': 'Техническая проблема',
    'support.catBilling': 'Оплата и тариф',
    'support.catFeature': 'Пожелание по функциям',
    'support.catData': 'Данные и отчёты',
    'support.catOther': 'Другое',
    'support.fieldDescription': 'Описание',
    'support.fieldDescriptionPh': 'Опишите проблему или вопрос подробнее…',
    'support.cancel': 'Отмена',
    'support.submitTicket': 'Отправить',
    'support.sending': 'Отправка…',
    'support.ticketSent': 'Обращение отправлено',
    'support.ticketSentDesc': 'Мы свяжемся с вами по email из аккаунта.',
    'support.subjectRequired': 'Укажите тему обращения',
    'support.descriptionRequired': 'Укажите описание',
    'support.ticketError': 'Не удалось отправить обращение',
    
    // Profile dialog
    'profile.title': 'Профиль',
    'profile.accountData': 'Данные аккаунта',
    'profile.name': 'Имя',
    'profile.email': 'Email',
    'profile.phone': 'Номер телефона',
    'profile.newPassword': 'Пароль',
    'profile.newPasswordPlaceholder': 'Новый пароль (оставьте пустым, чтобы не менять)',
    'profile.passwordMinLength': 'мин. 6 символов',
    'profile.showPassword': 'Показать пароль',
    'profile.hidePassword': 'Скрыть пароль',
    'profile.save': 'Сохранить',
    'profile.tariffPlan': 'Тарифный план',
    'profile.active': 'Активен',
    'profile.inactive': 'Не активен',
    'profile.validUntil': 'Действует до',
    'profile.daysRemaining': 'Осталось дней',
    
    // Language dialog
    'language.title': 'Выбор языка',
    'language.russian': 'Русский',
    'language.uzbek': 'Узбекский',

    // Pricing / Tariff dialog
    'pricing.extendTitle': 'Продлить тариф',
    'pricing.extendHeroTitle': 'Продлите тариф и развивайте бизнес с PROFiboard.',
    'pricing.extendHeroSubtitle': 'Выберите подходящий тариф и получайте точную аналитику для роста ваших продаж.',
    'pricing.extendHeroSubtitlePrefix': 'Выберите подходящий тариф и получайте точную аналитику ',
    'pricing.extendHeroSubtitleHighlight': 'для роста ваших продаж',
    'pricing.expiredTitle': 'Тариф закончился',
    'pricing.expiredHeroTitle': 'Тариф закончился — продлите доступ к PROFiboard',
    'pricing.chooseTariff': 'Выберите тариф',
    'pricing.subscription1Month': 'Подписка 1 месяц',
    'pricing.planStandard': 'Стандарт',
    'pricing.planBusiness': 'Бизнес',
    'pricing.launchPrice': 'Цена запуска',
    'pricing.forGrowingBusiness': 'Для растущего бизнеса',
    'pricing.upTo5Stores': 'До 5 магазинов',
    'pricing.upTo10Stores': 'До 10 магазинов',
    'pricing.dataAnyPeriod': 'Данные с начала года',
    'pricing.allFeatures': 'Все функции сервиса',
    'pricing.perMonth': 'сум / месяц',
    'pricing.selectTariff': 'Выбрать тариф',
    'pricing.limitedOffer': 'ОГРАНИЧЕННОЕ ПРЕДЛОЖЕНИЕ',
    'pricing.onePlusOne': '1+1 месяц бесплатно!',
    'pricing.onePlusOnePrefix': '1+1 месяц ',
    'pricing.onePlusOneHighlight': 'бесплатно!',
    'pricing.onePlusOneDesc': 'Оплатите первый месяц и получите второй месяц бесплатно.',
    'pricing.onePlusOneDescPrefix': 'Оплатите первый месяц и получите ',
    'pricing.onePlusOneDescHighlight': 'второй месяц бесплатно.',
    'pricing.promoTelegram': 'Подпишитесь на наш Telegram-канал',
    'pricing.promoTelegramBold': 'Подпишитесь',
    'pricing.promoTelegramRest': 'на наш Telegram-канал',
    'pricing.promoTelegramHint': 'быстрые ответы и помощь в первую очередь',
    'pricing.promoFeedback': 'Оставьте обратную связь о сервисе',
    'pricing.promoFeedbackBold': 'Оставьте обратную связь',
    'pricing.promoFeedbackRest': 'о сервисе',
    'pricing.promoParticipationTitle': 'Что нужно для участия:',
    'pricing.promoFeedbackHint': 'предлагайте улучшения и получайте сервис, который нужен именно вам',
    'pricing.select': 'Выбрать',
    'pricing.sum': 'сум',
    'pricing.month1': '1 месяц',
    'pricing.month3': '3 месяца',
    'pricing.month6': '6 месяцев',
    'pricing.year1': '1 год',
    'pricing.savings': 'Экономия',
    'pricing.popular': 'Популярный',
    'pricing.tryFree': 'Попробуй бесплатно',
    'pricing.tryFreeDesc': '10 дней полного доступа без оплаты',
    'pricing.startFree': 'Начать бесплатно',
    'pricing.cancelAnytime': 'Отмена подписки доступна в любой момент',
    'pricing.paymentTitle': 'Оплата тарифа',
    'pricing.qrPlaceholderTitle': 'Место для QR-кода',
    'pricing.qrPlaceholderHint': 'Разместите здесь QR-код для оплаты',
    'pricing.paymentNoticeLine1': 'Сейчас оплата доступна только по QR-коду.',
    'pricing.paymentNoticeLine2': 'В скором времени сервис дополниться другими способами оплаты.',
    'pricing.howToPayTitle': 'Как оплатить:',
    'pricing.stepOpenAppLine1': 'Откройте приложение для оплаты:',
    'pricing.stepOpenAppLine2': 'Payme, Click или приложение вашего банка.',
    'pricing.stepScanQr': 'Отсканируйте QR-код.',
    'pricing.stepEnterAmount': 'Введите сумму в соответствии с выбранным тарифом:',
    'pricing.month5Price': 'Month 5 — 190 000 сум',
    'pricing.month10Price': 'Month 10 — 280 000 сум',
    'pricing.stepScreenshot': 'Сделайте скриншот подтверждения оплаты.',
    'pricing.stepSendTelegramLine1': 'Отправьте скриншот оплаты и номер телефона (или почту), указанного при регистрации на сервис, в группу PROFiboard в Telegram ',
    'pricing.stepSendTelegramLine2': '(кнопка «Перейти в Telegram», откроется окно с QR-кодом для перехода).',
    'pricing.importantTitle': 'Важно:',
    'pricing.importantText': 'Доступ к выбранному тарифу будет открыт после подтверждения оплаты. Это может занять некоторое время.',
    'pricing.goToTelegram': 'Перейти в Telegram',
    'pricing.telegramTitle': 'Канал для отправки чека',

    // Report upload
    'report.uploadReports': 'Загрузить отчёты',
    'report.sales': 'Продажи',
    'report.expenses': 'Расходы',
    'report.inventory': 'Остатки',
    'report.storage': 'Хранение',
    
    // Actions
    'action.export': 'Экспорт',
    'action.import': 'Импорт',
    'action.apply': 'Применить',
    'action.cancel': 'Отмена',
    'action.close': 'Закрыть',
    
    // Common
    'common.from': 'от',
    'common.to': 'до',
    'common.or': 'или',
    'common.dataPeriod': 'Данные:',
    'common.lastUpdate': 'Обновлено:',
    'common.nextUpdate': 'Следующее обновление:',
    'common.renewTariffForUpdate': 'Продлите тариф для обновления данных.',
    'common.total': 'Итого',
    'common.pieces': 'шт',
    'common.sum': 'сум',

    // Summary page
    'summary.pageTitle': 'Мои продажи на',
    'summary.blockSales': 'ПРОДАЖИ',
    'summary.blockFinances': 'ФИНАНСЫ',
    'summary.blockExpenses': 'РАСХОДЫ',
    'summary.blockWarehouse': 'СКЛАД UZUM (FBO)',
    'summary.blockWarehouseFbs': 'Виртуальный склад (FBS)',
    'summary.blockUzumServices': 'УСЛУГИ UZUM',
    'summary.sales.orders': 'Заказы',
    'summary.sales.ordersTooltip': 'Общее кол-во заказов за выбранный период.',
    'summary.sales.processing': 'В обработке',
    'summary.sales.processingTooltip': 'Заказы по которым ожидается оплата.',
    'summary.sales.completed': 'Выкупы',
    'summary.sales.completedTooltip': 'Заказы которые клиент забрал, и прошло 10 дней.',
    'summary.sales.returns': 'Возвраты',
    'summary.sales.returnsTooltip': 'Заказы которые клиент вернул или отменил.',
    'summary.sales.returnRate': 'Процент возврата заказов',
    'summary.sales.returnRateTooltip': 'Отношение отменённых заказов к выкупленным заказам, выраженное в процентах.',
    'summary.sales.averageCheck': 'Средний чек',
    'summary.sales.averageCheckTooltip': 'Средняя стоимость заказа за период.',
    'summary.finance.revenue': 'Выручка',
    'summary.finance.revenueTooltip': 'Общая сумма денег, полученная вами от реализации товаров.',
    'summary.finance.expenses': 'Расходы',
    'summary.finance.expensesTooltip': 'Сумма всех метрик блока «Расходы» на этой вкладке.',
    'summary.finance.profit': 'Прибыль',
    'summary.finance.profitTooltip': 'Выручка – Расходы.',
    'summary.finance.salesProfitability': 'Рентабельность продаж',
    'summary.finance.salesProfitabilityTooltip': '(Прибыль / Выручка) × 100. Показывает, какая часть выручки является прибылью.',
    'summary.finance.roi': 'Окупаемость инвестиций',
    'summary.finance.roiTooltip': '(Прибыль / себестоимость товаров) × 100. Показывает, насколько выгодно вложение денег.',
    'summary.finance.revenueTrend': 'Тренд выручки',
    'summary.finance.revenueTrendTooltip': 'Сравнение выручки за выбранный текущий период с выручкой за аналогичный период ранее.',
    'summary.finance.lostRevenue': 'Упущенная выручка',
    'summary.finance.lostRevenueTooltip': 'Потенциальная потеря выручки за период из-за отсутствия товаров на складе = (кол-во дней без товара) × (средняя выручка за день) для всех товаров.',
    'summary.expense.commissionUzum': 'Комиссия UZUM',
    'summary.expense.logisticsUzum': 'Логистика UZUM',
    'summary.expense.productCost': 'Себест. прод. тов.',
    'summary.expense.productCostEditTooltip': 'Себестоимость из кабинета Uzum. Внесите актуальную себестоимость.',
    'summary.expense.taxes': 'Налоги',
    'summary.expense.taxesTooltip': 'Введите ставку налога и нажмите клавишу Enter.',
    'summary.expense.extraExpenses': 'Доп. расходы',
    'summary.expense.extraExpensesTooltip': 'Расходы, указанные вами во вкладке «Доп. расходы».',
    'summary.uzum.storage': 'Хранение UZUM',
    'summary.uzum.storageTooltip': 'Стоимость платного хранения товаров за выбранный период.',
    'summary.uzum.ads': 'Реклама UZUM',
    'summary.uzum.adsTooltip': 'Стоимость маркетинговых компаний (БУСТ в топ, БУСТ заказов, закрепленный отзыв) за выбранный период.',
    'summary.uzum.fines': 'Штрафы UZUM',
    'summary.uzum.finesTooltip': 'Начисленные штрафы за выбранный период.',
    'summary.warehouse.stock': 'Товаров на складе',
    'summary.warehouse.stockTooltip': 'Кол-во товаров, хранящихся на складе UZUM для продажи по FBO.',
    'summary.warehouse.fbsStockTooltip': 'Кол-во товаров на вашем складе для продажи по FBS.',
    'summary.warehouse.cost': 'Себест. тов.',
    'summary.warehouse.retailPrice': 'Рознич. цена',
    'summary.warehouse.retailPriceTooltip': 'Стоимость товаров, хранящихся на складе UZUM, при продаже их по ценам маркетплейса.',
    'summary.weeklyInsights.title': 'Ваш бизнес за последние 7 дней',
    'summary.weeklyInsights.collapse': 'Свернуть блок',
    'summary.weeklyInsights.expand': 'Развернуть блок',
    'summary.weeklyInsights.storagePrefix': 'Расходы за хранение ',
    'summary.weeklyInsights.storageChange': '{verb} на {percent}',
    'summary.weeklyInsights.storageSuffix': ' ({amount} сум)',
    'summary.weeklyInsights.storageIncreased': 'выросли',
    'summary.weeklyInsights.storageDecreased': 'уменьшились',
    'summary.weeklyInsights.minProfitBeforeName': 'Товар ',
    'summary.weeklyInsights.minProfitAfterName': ' принёс меньше всего прибыли → ',
    'summary.weeklyInsights.maxProfitBeforeName': 'Товар ',
    'summary.weeklyInsights.maxProfitAfterName': ' принёс больше всего прибыли → ',
    'summary.weeklyInsights.emptyIntroLink': 'Подключите API',
    'summary.weeklyInsights.emptyIntroSuffix': ' из личного кабинета Uzum и мы покажем:',
    'summary.weeklyInsights.emptyBullet1': 'какие товары приносят больше всего прибыли',
    'summary.weeklyInsights.emptyBullet2': 'где растут расходы и хранение',
    'summary.weeklyInsights.emptyBullet3': 'какие позиции убыточны',
    'summary.weeklyInsights.emptyBullet4': 'как меняются продажи и прибыль',
    'filter.allStores': 'Все магазины',
    'filter.lockedShop': 'Доступно на платном тарифе',
    'trialShop.title': 'Выберите магазин для просмотра',
    'trialShop.description': 'На Trial-тарифе доступна детальная аналитика одного магазина.',
    'trialShop.confirm': 'Продолжить',
    'trialShop.saving': 'Сохранение…',
    'trialShop.loadingShops': 'Загрузка списка магазинов…',
    'trialShop.noShopsYet': 'Магазины ещё не загружены. Дождитесь завершения синхронизации данных.',
    'filter.quickPeriod': 'Быстрый период',
    'filter.from': 'От',
    'filter.to': 'До',
    'filter.apply': 'Применить',
    'filter.reset': 'Сбросить',
    'filter.viewDay': 'По дням',
    'filter.viewWeek': 'По неделям',
    'filter.viewMonth': 'По месяцам',
    'filter.noSellsData': 'Нет данных sells-report',
    'filter.dateErrorOrder': 'Дата «От» не может быть позже «До»',
    'filter.dateErrorRange': 'Выберите даты в диапазоне данных',
    'tabs.expensesExtra': 'Доп. расходы',
    'tabs.shipmentLabel': 'Отгрузка',
    'tabs.monthly': 'Помесячно',
    'tabs.cogs': 'Себестоимость',

    // COGS tab
    'cogs.lkUzum': 'Себестоимость (Uzum)',
    'cogs.lkUzumLine1': 'Себестоимость',
    'cogs.lkUzumLine2': '(Uzum)',
    'cogs.actual': 'Себестоимость (актуальная)',
    'cogs.actualLine1': 'Себестоимость',
    'cogs.actualLine2': '(актуальная)',
    'cogs.unitMargin': 'Наценка',
    'cogs.calculation': 'Расчёт по данным',
    'cogs.calculationLine1': 'Расчёт',
    'cogs.calculationLine2': 'по данным',
    'cogs.date': 'Дата послед. изменения',
    'cogs.dateLine1': 'Дата послед.',
    'cogs.dateLine2': 'изменения',
    'cogs.actions': 'Действия',
    'cogs.sourceUzum': 'Uzum',
    'cogs.sourceProfiboard': 'Profiboard',
    'cogs.edit': 'Редактировать',
    'cogs.editTitle': 'Актуальная себестоимость',
    'cogs.effectiveFrom': 'Дата начиная с',
    'cogs.effectiveFromRequired': 'Укажите дату начиная с',
    'cogs.firstSaleDate': 'Дата первой продажи',
    'cogs.history': 'История',
    'cogs.historyTitle': 'Себестоимость по периодам',
    'cogs.historyEmpty': 'Нет данных о продажах и себестоимости',
    'cogs.historyPeriod': 'Период',
    'cogs.historyCogs': 'Себестоимость',
    'cogs.historyDelete': 'Удалить период',
    'cogs.historyDeleted': 'Период удалён',
    'cogs.historyDeleteError': 'Не удалось удалить период',
    'cogs.actualPlaceholder': 'Введите себестоимость',
    'cogs.loading': 'Загрузка…',
    'cogs.loadError': 'Не удалось загрузить себестоимость',
    'cogs.empty': 'Нет товаров. Загрузите отчёты.',
    'cogs.saved': 'Себестоимость сохранена',
    'cogs.saveError': 'Не удалось сохранить',
    'cogs.saving': 'Сохранение…',
    'cogs.invalidValue': 'Введите корректную сумму',
    'cogs.downloadTemplate': 'Скачать шаблон',
    'cogs.templateProducts': 'Шаблон товары',
    'cogs.templateProductsHint': 'Заполните себестоимость.',
    'cogs.templateEmpty': 'Пустой шаблон',
    'cogs.templateEmptyHint': 'Штрихкоды и себестоимость.',
    'cogs.uploadTemplate': 'Загрузить шаблон',
    'cogs.uploadLine1': 'Загрузить',
    'cogs.uploadLine2': 'Выбранный шаблон',
    'cogs.templateUploading': 'Загрузка…',
    'cogs.templateUploaded': 'Загружено строк: {count}',
    'cogs.templateUploadedNone': 'Нет строк для загрузки. Заполните себестоимость в шаблоне.',
    'cogs.templateDownloadError': 'Не удалось скачать шаблон',
    'cogs.templateUploadError': 'Не удалось загрузить шаблон',
    'cogs.templateEffectiveFromTitle': 'Дата применения себестоимости',
    'cogs.templateEffectiveFromHint': 'С этой даты будет действовать загружаемая себестоимость.',
    'cogs.templateAppliedTitle': 'Себестоимость применена',
    'cogs.templateAppliedMessage': 'Загружено строк: {count}. Себестоимость применена с {date}.',
    'cogs.templateAppliedOk': 'Понятно',
    'cogs.metricProducts': 'Товары',
    'cogs.metricWithoutCogs': 'Без себестоимости',
    'cogs.metricProfiboard': 'Расчёт ЛК Profiboard',
    'chart.salesByDay': 'Продажи по дням',
    'chart.noData': 'Загрузите отчеты',
    'header.loggedOut': 'Вы вышли из системы',
    'header.seller': 'Продавец',
    'header.settings': 'Настройки',
    'header.tariffs': 'Тарифы',

    // Chart axis & legend
    'chart.ordersPcs': 'Заказы, шт',
    'chart.revenueMlnSum': 'Выручка, млн сум',
    'chart.addComment': 'Добавить комментарий',
    'chart.date': 'Дата',
    'chart.selectDate': 'Выберите дату',
    'chart.comment': 'Комментарий',
    'chart.done': 'Готово',
    'chart.delete': 'Удалить',
    'chart.reallyOrders': 'реально',
    'chart.costsThousandSum': 'Затраты, тыс сум',
    'progress.mln': 'млн',
    'progress.billion': 'млрд',
    'progress.thousand': 'тыс',

    // Product detail
    'product.products': 'Товары',
    'product.productTitle': 'ТОВАР',
    'product.name': 'Название',
    'product.productType': 'Тип товара',
    'product.productId': 'ID товара',
    'product.ratingPrefix': 'рейтинг',
    'product.comment': 'Комментарий',
    'product.commentPlaceholder': 'Оставьте комментарий к товару...',
    'product.saving': 'Сохранение...',
    'product.save': 'Сохранить',
    'product.saveCommentError': 'Ошибка при сохранении комментария: {0}',
    'product.params': 'Параметры товара',
    'product.orders': 'Заказы',
    'product.stock': 'Остатки',
    'product.stockFbo': 'Остатки (FBO)',
    'product.stockFbs': 'Остатки (FBS)',
    'product.sizeGroup': 'Габ. группа',
    'product.barcode': 'Штрихкод',
    'product.storage': 'Хранение',
    'product.storageDaySum': 'сут/сум',
    'product.total': 'Всего',
    'product.noVariants': 'Нет вариантов товара',
    'product.marginality': 'Маржинальность',
    'product.revenueShare': 'От общей выручки',
    'product.selectPeriod': 'Выберите период в фильтре дат',

    // Daily view
    'daily.chartTitle': 'График заказов и продаж',
    'daily.dataByDay': 'Данные по дням',
    'daily.loading': 'Загрузка...',
    'daily.loadError': 'Ошибка загрузки данных',
    'daily.noDataPeriod': 'Загрузите отчеты',
    'daily.date': 'Дата',
    'daily.orders': 'Заказы',
    'daily.buys': 'Выкупы',
    'daily.returns': 'Возвраты',
    'daily.revenue': 'Выручка',
    'daily.commission': 'Комиссия',
    'daily.logistics': 'Логистика',
    'daily.storage': 'Хранение',
    'daily.ads': 'Реклама',
    'daily.penalties': 'Штрафы',
    'daily.cogs': 'Себестоимость',
    'daily.tax': 'Налог',
    'daily.profitNet': 'Чистая прибыль',
    'daily.granularityDay': 'День',
    'daily.granularityWeek': 'Неделя',
    'daily.granularityMonth': 'Месяц',
    'daily.exportXLSX': 'Выгрузить в XLSX',
    'daily.exportedRows': 'Выгружено {0} строк',
    'daily.exportError': 'Ошибка при выгрузке',

    // Monthly table
    'monthly.totalSold': 'Всего продано',
    'monthly.revenue': 'Выручка',
    'monthly.cost': 'Себестоимость',
    'monthly.commission': 'Комиссия',
    'monthly.logistics': 'Логистика',
    'monthly.storage': 'Хранение',
    'monthly.ads': 'Реклама',
    'monthly.fines': 'Штрафы',
    'monthly.tax': 'Налог',
    'monthly.extraExpenses': 'Доп. расходы',
    'monthly.netProfit': 'ЧИСТАЯ ПРИБЫЛЬ',
    'monthly.title': 'Финансовые показатели по всем магазинам',
    'monthly.year': 'год',
    'monthly.indicator': 'Показатель',

    // Products table columns
    'table.productName': 'Наименование',
    'table.turnover': 'Оборач-ть',
    'table.sizeGroup': 'Габаритная группа',
    'table.storagePerDay': 'Хранение сут/сум',
    'table.shop': 'Магазин',
    'table.abcOrders': 'ABC заказы',
    'table.abcProfit': 'ABC прибыль',
    'table.abcRevenue': 'ABC выручка',
    'table.noDataProducts': 'Загрузите отчеты',

    // Report upload
    'report.salesReport': 'Отчет по продажам',
    'report.expensesReport': 'Отчет по услугам',
    'report.storageReport': 'Отчет по хранению',
    'report.inventoryOld': 'Остатки (старый формат)',

    // Expenses
    'expense.date': 'Дата',
    'expense.save': 'Сохранить',
    'expense.add': 'Добавить',
    'expense.type': 'Тип',
    'expense.amount': 'Сумма',
    'expense.actions': 'Действия',
    'expense.loading': 'Загрузка...',
    'expense.noExpensesAdded': 'Добавьте расходы',
    'expense.editDesc': 'Измените данные расхода',
    'expense.addDesc': 'Заполните форму для добавления нового расхода',
    'expense.selectDate': 'Выберите дату',

    // Report upload (screenshots)
    'report.uploadButton': 'Загрузить отчеты',
    'report.uploadTitle': 'Загрузка отчетов UZUM',
    'report.uploadDialogMainTitle': '4 базовых отчета Uzum необходимых для анализа.',
    'report.guidedHeroTitle': 'Получите аналитику продаж и прибыли за 2 минуты',
    'report.guidedHeroSubtitle':
      'Загрузите 4 отчета из личного кабинета Uzum — и мы покажем, что приносит прибыль, а что тянет ваш бизнес вниз.',
    'report.guidedBenefitsHeading': 'Что вы получите после загрузки',
    'report.guidedBenefit1Title': 'Прибыль и реальные',
    'report.guidedBenefit1Desc': 'показатели по дням',
    'report.guidedBenefit2Title': 'Топ прибыльные',
    'report.guidedBenefit2Desc': 'и убыточные товары',
    'report.guidedBenefit3Title': 'Все расходы',
    'report.guidedBenefit3Desc': 'и комиссии Uzum',
    'report.guidedBenefit4Title': 'Остатки и хранение',
    'report.guidedBenefit4Desc': 'товаров',
    'report.guidedBenefit5Title': 'Тренды и динамика',
    'report.guidedBenefit5Desc': 'продаж',
    'report.guidedDataSafetyTitle': 'Ваши данные в безопасности',
    'report.guidedDataSafetyBody':
      'Мы не передаем данные третьим лицам. Вы можете удалить их в любой момент.',
    'report.guidedStep1Title': 'Скачайте 4 отчета из ЛК Uzum',
    'report.guidedStep1Body':
      '1. Сформируйте 4 отчета: Продажи, Услуги, Остатки (старый формат), Хранение.\n2. Сохраните в формате XLSX на компьютер.',
    'report.guidedStep1Footnote':
      'Отчеты должны быть все за один период. Рекомендуем выгружать отчеты с начала года.',
    'report.guidedStep2Title': 'Загрузите 4 отчета в PROFiboard',
    'report.guidedStep2Body':
      '1. Нажмите на кнопку «Загрузить отчеты» в шапке сервиса PROFiboard.\n2. Перетащите файлы или нажмите на окно загрузки.',
    'report.guidedSocialProofBold': '98% продавцов',
    'report.guidedSocialProofRest':
      'уже получают аналитику через 2 минуты после первой загрузки отчетов',
    'report.guidedDemoHeading': 'Не хотите загружать сейчас?',
    'report.guidedDemoSubtitle': 'Посмотрите демо-дашборд с примерами реальных данных.',
    'report.guidedDemoButton': 'Посмотреть демо',
    'report.guidedDemoPreviewAlt': 'Превью демо-дашборда PROFiboard',
    'report.guidedTelegramHelpTitle': 'Нужна помощь с первой загрузкой?',
    'report.guidedTelegramHelpBody':
      'Ответим в течение 5 минут в Telegram и поможем шаг за шагом.',
    'report.uploadStepsHeading': 'Как скачать отчёты в ЛК и загрузить файлы в PROFiboard',
    'report.watchImportVideo': 'Смотреть видео',
    'report.watchImportVideoGuided': 'Смотреть видео (~2 мин)',
    'report.importVideoModalTitle': 'Импорт отчётов',
    'report.firstUploadHelp': 'Если нужна помощь с первой загрузкой — обращайтесь в Telegram, мы поможем.',
    'report.openTelegram': 'Открыть Telegram',
    'report.uploadFilesSectionTitle': 'Загрузка файлов',
    'report.howItWorks': 'Как это работает?',
    'report.bullet1': 'Загрузите отчёты XLSX из личного кабинета UZUM',
    'report.bullet2': 'Система автоматически распознает тип отчёта и импортирует данные',
    'report.bullet3': 'ВАЖНО: Все отчёты должны быть за один период',
    'report.dragOrClick': 'Перетащите файлы или нажмите',
    'report.close': 'Закрыть',
    'report.stepImageZoomAria': 'Увеличить изображение',
    'report.uploadFilesButton': 'Загрузить файлы',
    'report.upload': 'Загрузить',
    'report.lastUpload': 'Последняя загрузка',
    'report.uploadingReports': 'Загрузка отчётов...',
    'report.storeLimitExceeded': 'Превышение допуска по магазинам',
    'storeLimit.title': 'Достигнут лимит магазинов',
    'storeLimit.description': 'Ваш тариф {currentTariff} позволяет подключить до {max} магазинов. Чтобы добавить новый магазин, обновите тариф.',
    'storeLimit.connected': 'Подключено: {current} / {max}',
    'storeLimit.upgradeButton': 'Перейти на тариф {nextTariff}',
    'storeLimit.contactSupport': 'Для увеличения магазинов, обратитесь в поддержку',
    'report.importedRows': 'Импортировано: {0} строк',
    'report.onlyLeftout': 'Принимается только left-out-report_old',
    'report.productAdLink': 'Связь товаров с рекламой',
    'report.adLinkDesc': 'Укажите ID рекламных кампаний для точного расчёта затрат на продвижение каждого товара.',
    'report.enterAdId': 'Введите ID рекламы',
    'report.adId': 'ID рекламы',
    'report.loadError': 'Ошибка загрузки данных',
    'shipment.noDataHint': 'Загрузите отчеты',
    'search.byNameArticle': 'Поиск по названию, артикулу...',
    'products.enterCogs': 'Внести себестоимость',
    'products.groupByCards': 'Сгруппировать по карточкам',
    'products.loading': 'Загрузка товаров…',
    'products.updating': 'Обновление данных…',
    'products.loadError': 'Не удалось загрузить товары. Попробуйте обновить страницу.',
    'expense.howItWorks': 'Как это работает?',
    'howItWorks.triggerLabel': 'Как это работает?',
    'howItWorks.triggerTooltip': 'Подсказка по всем вкладкам',
    'howItWorks.triggerAria': 'Открыть подсказку по всем вкладкам',
    'howItWorks.panelTitle': 'Как работает вкладка «{tab}»',
    'expense.howItWorks1': 'Здесь можно вручную добавить любые дополнительные расходы, которые не передаются по выгрузке в отчетах или через API из маркетплейса',
    'expense.howItWorks2': 'Примеры расходов - самовыкупы, зарплата, внешняя реклама, своя логистика и т.д.',
    'expense.howItWorks3': 'Расходы будут учитываться во всех отчетах с финансами для выбранной даты и магазина/товара (если указаны)',
    'expense.howItWorks4': 'Если не указаны — расходы будут добавлены в месячный отчет в общем',
    'howItWorks.summary.item1': 'На вкладке представлена детализация ключевых метрик: Продажи, Финансы, Расходы, Склад и Услуги Uzum.',
    'howItWorks.summary.itemCogsBefore': 'Для точного подсчета прибыли ',
    'howItWorks.summary.itemCogsLink': 'укажите актуальную себестоимость',
    'howItWorks.summary.itemCogsAfter': ' ваших товаров.',
    'howItWorks.summary.item2Before': 'Значок',
    'howItWorks.summary.item2After': 'у каждого показателя даёт краткую справку о нём.',
    'howItWorks.summary.item3': 'Блок «Ваш бизнес за последние 7 дней» показывает быстрые инсайты по прибыли и хранению.',
    'howItWorks.summary.item4': 'В правой части представлены фильтры: вы можете выбрать временной период и магазин, который хотите посмотреть.',
    'howItWorks.daily.item1': 'Выберите метрику на графике (Заказы, Возвраты, Выручка и т.д.) для просмотра изменения её на периоде.',
    'howItWorks.daily.item2': 'Используйте фильтры по периоду и группировке: по дням, неделям или месяцам — график перестроится соответственно.',
    'howItWorks.daily.item3': 'В таблице под графиком вы можете упорядочить данные по всем метрикам; данные можно выгрузить в Excel.',
    'howItWorks.products.item1': 'Используйте основные фильтры в правой части, чтобы выбрать период или магазин.',
    'howItWorks.products.item2': 'Используйте «Сгруппировать по карточкам», чтобы объединить все однотипные товары.',
    'howItWorks.products.item3': 'Нажмите на товар, чтобы открыть данные по нему и оставить комментарий, если это необходимо.',
    'howItWorks.products.item4': 'Используйте знак сортировки в заголовках столбцов, чтобы упорядочивать данные в таблице.',
    'howItWorks.shipment.item1': 'Используйте основные фильтры в правой части, чтобы выбрать магазин.',
    'howItWorks.shipment.item2': 'Укажите, через сколько дней вы планируете отгрузить товар на склад UZUM (FBO) — сервис посчитает, сколько товара нужно привезти, чтобы он не попал на платное хранение.',
    'howItWorks.shipment.item3': 'Вы можете выгрузить список ваших товаров к отгрузке в Excel.',
    'howItWorks.monthly.item1': 'Во вкладке представлены данные по всем вашим магазинам за каждый месяц.',
    'howItWorks.monthly.item2': 'В доп. расходах указаны все ваши расходы, которые вы записали во вкладке «Доп. расходы».',
    'howItWorks.monthly.item3': 'Налог рассчитывается из расчёта указанного вами % во вкладке «Сводка».',
    'howItWorks.cogs.item1': 'Для точного подсчета прибыли важно указывать актуальную себестоимость ваших товаров. В приоритете мы используем данные о себестоимости из PROFIboard и если они не заполнены, то из кабинета продавца UZUM.',
    'howItWorks.cogs.item2': 'Вы можете изменять данные для каждого товара отдельно, либо скачать, заполнить шаблон и загрузить данные массово.',
    'howItWorks.cogs.item3': 'Важно! Если с течением года, ваша себестоимость товаров изменялась, вы можете указать себестоимость товара для каждого периода. Так данные будут максимально точными.',
    'howItWorks.cogs.item4': 'Если вы вводите себестоимость первый раз, применяйте дату с начала года (1.01.)',
    'expense.addExpense': 'Добавить расход',
    'expense.editExpense': 'Редактировать расход',
    'expense.typeLabel': 'Тип расхода',
    'expense.selectType': 'Выберите тип',
    'expense.notSelected': 'Не выбран',
    'expense.notSelectedItem': 'Не выбрано',
    'expense.selectShopOptional': 'Выберите магазин (опционально)',
    'expense.selectNameOptional': 'Выберите наименование (опционально)',
    'expense.noShopsAvailable': 'Нет доступных магазинов (загрузите seller-storage)',
    'expense.noNamesAvailable': 'Нет доступных наименований (загрузите left-out-report_old)',
    'expense.commentOptional': 'Добавьте комментарий (опционально)',
    'expense.typeSelfBuy': 'Самовыкуп',
    'expense.typeSalary': 'Зарплата',
    'expense.typeExternalAds': 'Внешняя реклама',
    'expense.typeOwnLogistics': 'Своя логистика',
    'expense.typePackaging': 'Упаковка',
    'expense.typeRent': 'Аренда',
    'expense.typeOther': 'Прочее',
    'shipment.daysUntil': 'Дней до отгрузки на склад Uzum',
    'shipment.daysCount': 'Количество дней',
    'shipment.daysDescription': 'Укажите через сколько дней планируется отгрузка товара начиная с даты выгрузки последнего отчета',
    'shipment.considerStock': 'Учитывать остатки на складах',
    'shipment.yes': 'Да',
    'shipment.no': 'Нет',
    'shipment.calculate': 'Рассчитать',
    'shipment.calculating': 'Расчёт…',
    'shipment.recommendations': 'Рекомендации по отгрузке',
    'shipment.exportXLSX': 'Выгрузить в XLSX',
    'shipment.product': 'Товар',
    'shipment.article': 'Артикул',
    'shipment.inStock': 'На складе',
    'shipment.salesPerDay': 'Продаж в день',
    'shipment.recommendedQty': 'Рекомендуемое кол-во',
    'shipment.plannedToShip': 'Запланировано к отгрузке',
    'shipment.calculationDone': 'Расчет данных окончен',
    'shipment.exportedRows': 'Выгружено {0} строк',
    'shipment.exportError': 'Ошибка при выгрузке',
    'monthly.jan': 'Янв',
    'monthly.feb': 'Фев',
    'monthly.mar': 'Мар',
    'monthly.apr': 'Апр',
    'monthly.may': 'Май',
    'monthly.jun': 'Июн',
    'monthly.jul': 'Июл',
    'monthly.aug': 'Авг',
    'monthly.sep': 'Сен',
    'monthly.oct': 'Окт',
    'monthly.nov': 'Ноя',
    'monthly.dec': 'Дек',

    // Index alerts
    'alert.noStockData': 'Загрузите отчеты',
    'alert.stockZero': 'Склад = 0',
    'alert.stockZeroDesc': 'По данным left-out-report_old на складе 0. Проверь выгрузку «Склад» или фильтр магазина.',
    'alert.stockZeroReasonAll': 'По последней выгрузке склада (left-out-report_old) сумма «В продаже» = 0. Проверь файл склада/остатков.',
    'common.snapshot': 'Срез',
    // Stock daily chart tooltips
    'stockDaily.title': 'Складские остатки по дням',
    'stockDaily.noData': 'Нет данных по складу за период',
    'stockDaily.orders': 'Заказы',
    'stockDaily.stock': 'Товары на складе',
    'stockDaily.stockAxis': 'Товары на складе, шт',
    // Category chart
    'categoryChart.title': 'Продажи по категориям',
    'categoryChart.subtitle': 'Топ категории за месяц',
    'categoryChart.tooltipSales': 'Продажи',
    // Analytics revenue chart
    'analytics.revenueOrdersTitle': 'Выручка и заказы',
    'analytics.revenueOrdersSubtitle': 'Динамика за период',
    // Sidebar
    'sidebar.toggle': 'Свернуть/развернуть меню',
    // Admin panel tabs
    'admin.tabs.overview': 'Обзор',
    'admin.tabs.uzum': 'API',
    'admin.tabs.uzumUsers': 'API user',
    'admin.tabs.archive': 'Архив',
    'admin.uzumSyncLogs.title': 'Логи обновления Uzum API',
    'admin.uzumSyncLogs.subtitle': 'Автоматическое и ручное обновление данных по расписанию (06:00 и 18:00, Asia/Tashkent)',
    'admin.uzumSyncLogs.refresh': 'Обновить',
    'admin.uzumSyncLogs.exportExcel': 'Выгрузить Excel',
    'admin.uzumSyncLogs.exporting': 'Выгрузка…',
    'admin.uzumSyncLogs.exportEmpty': 'Нет записей для выгрузки',
    'admin.uzumSyncLogs.exportFailed': 'Не удалось выгрузить Excel',
    'admin.uzumSyncLogs.selectAll': 'Выделить все',
    'admin.uzumSyncLogs.deselectAll': 'Снять выделение',
    'admin.uzumSyncLogs.deleteSelected': 'Удалить',
    'admin.uzumSyncLogs.deleting': 'Удаление…',
    'admin.uzumSyncLogs.deleteSuccess': 'Удалено записей',
    'admin.uzumSyncLogs.deleteFailed': 'Не удалось удалить записи',
    'admin.uzumSyncLogs.selectRow': 'Выделить строку',
    'admin.uzumSyncLogs.metricActive': 'Active',
    'admin.uzumSyncLogs.metricDays': 'Days',
    'admin.uzumSyncLogs.metricSuccess': 'Success',
    'admin.uzumSyncLogs.metricFailed': 'Failed',
    'admin.uzumSyncLogs.metricSuccessRate': 'Успех, %',
    'admin.uzumSyncLogs.metricManual': 'Manual',
    'admin.uzumSyncLogs.metricScheduled': 'Scheduled',
    'admin.uzumSyncLogs.userId': 'user_id',
    'admin.uzumSyncLogs.email': 'Email',
    'admin.uzumSyncLogs.startedAt': 'Начало',
    'admin.uzumSyncLogs.finishedAt': 'Завершение',
    'admin.uzumSyncLogs.duration': 'Время',
    'admin.uzumSyncLogs.status': 'Статус',
    'admin.uzumSyncLogs.trigger': 'Источник',
    'admin.uzumSyncLogs.lastSync': 'Последний успешный sync',
    'admin.uzumSyncLogs.error': 'Ошибка',
    'admin.uzumSyncLogs.errorDetailTitle': 'Полный текст ошибки',
    'admin.uzumSyncLogs.loading': 'Загрузка…',
    'admin.uzumSyncLogs.empty': 'Записей пока нет',
    'admin.uzumSyncLogs.page': 'Страница',
    'admin.uzumSyncLogs.prev': 'Назад',
    'admin.uzumSyncLogs.next': 'Вперёд',
    'admin.archive.description': 'Ручная загрузка отчётов из личного кабинета Uzum (XLSX).',
    // Admin subscriptions and tooltips
    'admin.subscriptions.title': 'Аналитика подписок',
    'admin.subscriptions.revenue': 'Доход (сум)',
    'admin.subscriptions.subscribers': 'Подписчики',
    'admin.monthly.registrationsHelp': 'Количество зарегистрированных пользователей за месяц',
    'admin.tooltip.disableTenant': 'Отключить',
    'admin.tooltip.enableTenant': 'Включить',
    'admin.tooltip.extendTrial': 'Добавить дни триала',
    'admin.tooltip.recordPayment': 'Записать платёж',
    'admin.tooltip.changePassword': 'Изменить / сбросить пароль',
    'admin.tooltip.deleteTenant': 'Удалить аккаунт и данные',
    'admin.tooltip.uzumSync': 'Обновить подключение к Uzum API',
  },
  uz: {
    // Navigation
    'nav.dashboard': 'Boshqaruv paneli',
    'nav.products': 'Tovarlar (mahsulotlar)',
    'nav.analytics': 'Tahlil',
    'nav.competitors': 'Raqobatchilar',
    'nav.trends': 'Trendlar',
    'nav.reports': 'Hisobotlar',
    'nav.support': 'Qo\'llab-quvvatlash Xizmati',
    'nav.training': "O'qitish",

    // Training (video playlist)
    'learning.title': "O'qitish",
    'learning.subtitle': "Xizmat bo'yicha video darsliklar",
    'learning.back': 'Orqaga',
    'learning.playlist': 'Darsliklar',
    'learning.videoLoadError': "Video yuklanmadi.",
    'learning.videoNoHtml5': "Brauzeringiz video qo'llab-quvvatlamaydi.",
    'learning.videoSummary.title': 'Svodka',
    'learning.videoSummary.desc': 'Svodka varaqlari, filtrlar va metrikalar',
    'learning.videoByDay.title': 'Kunlik',
    'learning.videoByDay.desc': 'Kunlar bo‘yicha savdo va foyda dinamikasi',
    'learning.videoGoods.title': 'Tovarlar',
    'learning.videoGoods.desc': 'Tovarlar jadvali, kartochkalar va ABC-tahlil',
    'learning.videoAdditionalExpenses.title': 'Dop. xarajatlar',
    'learning.videoAdditionalExpenses.desc': 'Standart bo‘limlardan tashqari xarajatlarni hisobga olish',
    'learning.videoShipment.title': 'Jo‘natma',
    'learning.videoShipment.desc': 'Jo‘natish uchun tavsiya etilgan miqdorni hisoblash',
    'learning.videoMonthly.title': 'Oylik',
    'learning.videoMonthly.desc': 'Oylik savdo va foyda tahlili',

    // Tabs
    'tabs.summary': 'Hisobotlar',
    'tabs.products': 'Mahsulotlar',
    'tabs.daily': 'Kunlik',
    'tabs.expenses': 'Xarajatlar',
    'tabs.shipment': 'Yetkazib berish',
    'tabs.services': 'Xizmatlar',

    // Uzum API services tab
    'services.title': 'UZUM Seller API ulanishi',
    'services.description': 'Uzum shaxsiy kabinetidan integratsiya kalitini kiriting: Sozlamalar → API kalitlari',
    'services.descriptionInstruction': 'Qanday qilish kerak? (Qo‘llanma)',
    'services.instructionTitle': 'Uzum shaxsiy kabinetidan integratsiya kalitini kiriting:',
    'services.instructionStep1Prefix': 'Uzum shaxsiy kabinetiga kiring → ',
    'services.instructionStep1Link': 'Sozlamalar → API kalitlari',
    'services.instructionStep1Suffix': '.',
    'services.instructionStep2': 'Kalit yarating.',
    'services.instructionStep2GuideLink': 'API ulash: 3 qadamda',
    'services.instructionStep3': 'Kalitni PROFiboard xizmatidagi ulanish oynasiga nusxalang.',
    'services.instructionImportant': 'MUHIM: Ulanish 4 dan 10 daqiqagacha vaqt oladi.',
    'services.descriptionOpenApi': 'Uzum Market rasmiy sotuvchi OpenAPIʼsini o‘rganing. Kalit seller.uzum.uz kabinetida yaratiladi.',
    'services.apiKeyHintSaved': 'Kalit hisobingizda saqlanadi. Almashtirish uchun yangisini kiriting va «Ulash» bosing.',
    'services.apiKeyBearerHint': 'Faqat tokenni kiriting, Bearer so‘zisiz — Uzum: Authorization: <token>.',
    'services.apiKeyLabel': 'Uzum API kaliti',
    'services.apiKeyPlaceholder': 'Sotuvchi kabinetidan kalitni kiriting',
    'services.apiKeyHint': 'Ulanish 4 dan 10 daqiqagacha vaqt oladi.',
    'services.keyInvalid': 'Kalit Uzum API tomonidan qabul qilinmadi',
    'services.keyInvalidUserMessage': "Noto'g'ri kalit. Kalitni kiriting yoki qo'llab-quvvatlash bilan bog'laning",
    'services.keyInsufficientAccessUserMessage': "Kalit qabul qilindi, lekin ma'lumotlarni yuklash uchun huquqlar yetarli emas. Uzum Seller'da kalit yaratishda do'konlar va buyurtmalar/moliya/mahsulotlar ruxsatlarini tanlang. Xato takrorlansa, qo'llab-quvvatlash bilan bog'laning.",
    'services.shopUnavailableUserMessage': "Kalit qabul qilindi, lekin do'kon API uchun mavjud emas. Uzum Seller kabinetida do'kon holatini tekshiring yoki boshqa hisob kalitidan foydalaning.",
    'services.keyWarningTitle': 'API kalitini tekshiring',
    'services.apiKeyRequired': 'API kalitini kiriting',
    'services.connect': 'Ulash',
    'services.connectInProgress': 'Ulanish va maʼlumotlarni yuklash…',
    'services.connectStepApi': 'API ga ulanmoqdamiz…',
    'services.connectStepSales': 'Sotuvlarni tahlil qilmoqdamiz…',
    'services.connectStepProfit': 'Foydani hisoblaymiz…',
    'services.connectStepDashboard': 'Dashboard yig‘moqdamiz…',
    'services.connectFailed': 'Uzum API ga ulanib bo‘lmadi',
    'services.noSavedApiKey': 'Avval API ni ulang — saqlangan kalit topilmadi',
    'services.refreshFailed': 'Saqlangan API kalitini olish mumkin emas',
    'services.swaggerLink': 'Uzum Swagger hujjatlari',
    'services.errorTitle': 'Xato',
    'services.endpointsTitle': 'Mavjud API metodlari',
    'services.endpointsCount': 'endpoint',
    'services.responseTitle': 'API javobi',
    'services.responseHint': 'Maʼlumotlarni ko‘rish uchun ▶ tugmasini bosing',
    'services.pickEndpoint': 'Chapdan metod tanlang va ▶ bosing',
    'services.loading': 'Uzum ga so‘rov…',
    'services.tryRequest': 'So‘rov yuborish',
    'services.untagged': 'Kategoriyasiz',
    'services.exportTitle': 'Xizmatga yuklash uchun hisobotlar',
    'services.exportDescription': 'Qo‘lda yuklashdagi kabi XLSX (sells-report, expenses-report va boshqalar). Maʼlumot Uzum Seller API dan.',
    'services.exportBoldHint': 'API da yo‘q ustunlar Excel va ko‘rinishda qalin — kataklar bo‘sh qoladi.',
    'services.exportFailed': 'Faylni yuklab bo‘lmadi',
    'services.previewFailed': 'Ko‘rib chiqishni yuklab bo‘lmadi',
    'services.preview': 'Ko‘rish',
    'services.previewTitle': 'Ko‘rib chiqish',
    'services.previewShown': 'ko‘rsatildi',
    'services.rows': 'qator',
    'services.noRows': 'Tanlangan davr uchun maʼlumot yo‘q',
    'services.columnsFromApi': 'ustun API dan',
    'services.dateFrom': 'dan',
    'services.dateTo': 'gacha',
    'services.skippedShops': "Ba'zi do'konlar o'tkazib yuborildi — Uzum moliyaviy API da ruxsat yo'q.",
    'services.rateLimit': "Uzum so'rovlar tezligini chekladi. 1–2 daqiqa kutib qayta urinib ko'ring.",
    'services.loadData': 'Maʼlumotlarni yuklash',
    'services.loadDataInProgress': 'Maʼlumotlar yuklanmoqda…',
    'services.loadDataHint': "Yil boshidan 4 ta hisobotni Uzum API dan yuklab, xizmatga import qiladi.",
    'services.loadDataSuccess': 'Maʼlumotlar yuklandi',
    'services.syncRequestInterrupted': "So'rovni yakunlab bo'lmadi. Agar yuklash boshlangan bo'lsa, u serverda davom etishi mumkin. Bir necha daqiqadan so'ng holatni tekshiring.",
    'services.loadDataFailed': 'Maʼlumotlarni yuklab bo‘lmadi',

    // Help → API ulash (arxivdan alohida nusxa)
    'helpConnectApi.heroTitle': 'API ulash: 3 qadamda',
    'helpConnectApi.watchVideo': 'Videoni tomosha qilish (~2 daqiqa)',
    'helpConnectApi.benefitsHeading': 'Yuklashdan keyin nima olasiz',
    'helpConnectApi.benefit1Title': 'Foyda va haqiqiy',
    'helpConnectApi.benefit1Desc': 'kunlar bo‘yicha ko‘rsatkichlar',
    'helpConnectApi.benefit2Title': 'Eng foydali',
    'helpConnectApi.benefit2Desc': 'va zararli tovarlar',
    'helpConnectApi.benefit3Title': 'Barcha xarajatlar',
    'helpConnectApi.benefit3Desc': 'va Uzum komissiyalari',
    'helpConnectApi.benefit4Title': 'Qoldiqlar va saqlash',
    'helpConnectApi.benefit4Desc': 'tovarlari',
    'helpConnectApi.benefit5Title': 'Trendlar va dinamika',
    'helpConnectApi.benefit5Desc': 'savdosi',
    'helpConnectApi.dataSafetyTitle': 'Ma’lumotlaringiz xavfsiz',
    'helpConnectApi.dataSafetyBody':
      'Uchinchi shaxslarga bermaymiz. Istalgan vaqtda o‘chirib tashlashingiz mumkin.',
    'helpConnectApi.step1Title': 'UZUM Seller API ulanishi',
    'helpConnectApi.step1Line2': '2. Kalit yarating.',
    'helpConnectApi.step1Line3': '3. Kalitni PROFiboard xizmatidagi ulanish oynasiga nusxalang.',
    'helpConnectApi.step1Footnote': 'Ulanish 4 dan 10 daqiqagacha vaqt oladi.',
    'helpConnectApi.whileConnectingText':
      '✨ Bir necha daqiqadan so‘ng do‘koningiz tahlilini real vaqt rejimida ko‘ra olasiz. Ulanish davomida dashbord sharhini ko‘ring: qaysi tovarlar foyda keltirishi, xarajatlar qayerda o‘sishi va birinchi navbatda nimalarga e’tibor berish kerakligini bilib oling.',
    'helpConnectApi.dashboardOverviewButton': 'Dashbord sharhini ko‘rish',
    'helpConnectApi.step2Title': 'PROFiboard’ga 4 ta hisobotni yuklang',
    'helpConnectApi.step2Body':
      '1. PROFiboard sarlavhasidagi «Hisobotlarni yuklash» tugmasini bosing.\n2. Fayllarni sudrab tashlang yoki yuklash oynasini bosing.',
    'helpConnectApi.socialProofBold': 'Sotuvchilarning 98%',
    'helpConnectApi.socialProofRest':
      'hisobotlarni birinchi marta yuklaganidan keyin 2 daqiqada tahlil oladi.',
    'helpConnectApi.demoHeading': 'Hozir yuklamoqchi emasmisiz?',
    'helpConnectApi.demoSubtitle': 'Haqiqiy ma’lumotlar bilan demo-dashbordni ko‘ring.',
    'helpConnectApi.demoButton': 'Demoni ko‘rish',
    'helpConnectApi.demoPreviewAlt': 'PROFiboard demo-dashbord ko‘rinishi',
    'helpConnectApi.telegramHelpTitle': 'Birinchi yuklashda yordam kerakmi?',
    'helpConnectApi.telegramHelpBody':
      'Telegramda 5 daqiqa ichida javob beramiz va qadam-baqadam yordam beramiz.',

    // Filters
    'filter.today': 'Bugun',
    'filter.yesterday': 'Kecha',
    'filter.week': 'Hafta',
    'filter.month': 'Oy',
    'filter.year': 'Yil',
    'filter.period': 'Davr',
    'filter.all': 'Hammasi',
    'filter.excess': 'Ortiqcha',
    'filter.outOfStock': 'Omborda yo\'q',
    'filter.needSupply': 'Yetkazish kerak',
    
    // KPI Cards
    'kpi.revenue': 'Tushum',
    'kpi.orders': 'Buyurtmalar',
    'kpi.returns': 'Qaytarishlar',
    'kpi.profit': 'Foyda',
    'kpi.marginality': 'Umumiy daromadning marginalligi',
    'kpi.averageCheck': "O'rtacha chek",
    
    // Blocks
    'block.finances': 'Moliya',
    'block.expenses': 'Xarajatlar',
    'block.warehouse': 'Ombor',
    'block.revenueProgress': "Jami daromad",
    
    // Finance items
    'finance.revenue': 'Tushum',
    'finance.logistics': 'Logistika xizmatlari',
    'finance.commission': 'Komissiya miqdori',
    'finance.promoDiscount': 'Aksiya chegirmasi',
    'finance.netRevenue': 'Sof daromad',
    
    // Expense items
    'expense.soldGoodsCost': "Sotilgan tovarlar tannarxi",
    'expense.logistics': 'Logistika xizmatlari',
    'expense.commission': 'Komissiya miqdori',
    'expense.promoDiscount': 'Aksiya chegirmasi',
    'expense.advertising': 'Reklama',
    'expense.fines': 'Jarimalar',
    'expense.storage': 'Saqlash xizmati',
    'expense.other': 'Boshqa',
    'expense.total': 'Jami xarajatlar',
    
    // Warehouse items
    'warehouse.warehouseStock': "Ombordagi tovar tannarxi",
    'warehouse.potentialRevenue': 'Potentsial daromad',
    'warehouse.potentialProfit': 'Potentsial foyda',
    
    // Table headers
    'table.product': 'Tovar',
    'table.article': 'Artikul',
    'table.category': 'Kategoriya',
    'table.costPrice': 'Tannarx',
    'table.price': 'Narx',
    'table.orders': 'Buyurtmalar',
    'table.returns': 'Qaytarishlar',
    'table.stock': 'Qoldiqlar',
    'table.stockFbo': 'Qoldiq (FBO)',
    'table.stockFbs': 'Qoldiq (FBS)',
    'table.availability': 'Mavjudlik',
    'table.revenue': 'Tushum',
    'table.profit': 'Foyda',
    'table.margin': 'Marja',
    
    // Availability status
    'availability.excess': 'Ortiqcha',
    'availability.outOfStock': "Omborda yo'q",
    'availability.needSupply': 'Yetkazish kerak',
    
    // Header
    'header.search': "Mahsulot, kategoriya qidirish...",
    'header.notifications': 'Bildirishnomalar',
    'header.notificationsTooltip': 'Reyting, jarimalar va marketpleysning boshqa ushlab qolishlari.',
    'notification.lowRating': 'Mahsulot reytingi 4.5 dan pastga tushdi',
    'notification.openProductCard': 'Mahsulot kartasini ochish',
    'header.allNotifications': 'Barcha bildirishnomalar',
    'header.noNotifications': 'Bildirishnomalar yo‘q',
    'header.deleteNotification': 'Bildirishnomani o‘chirish',
    'header.deleteAllNotifications': 'Hammasini o‘chirish',
    'header.help': 'Yordam',
    'header.helpTooltip': 'Qo‘llanma, video darslar va qo‘llab-quvvatlash',
    'header.helpUploadReports': 'Hisobotlarni yuklash',
    'header.helpConnectApi': 'API ulash: 3 qadamda',
    'header.enterCogs': 'Tannarxni kiritish',
    'header.connectApi': 'API ulash',
    'header.refreshApi': 'Maʼlumotlarni yangilash',
    'header.refreshApiTooltip': 'Uzum API orqali maʼlumotlarni yangilash',
    'header.apiConnected': 'API ulandi',
    'header.videoTutorials': 'Video- darsliklar',
    'header.support': "Qo'llab-quvvatlash bilan bog'lanish",
    'header.myAccount': 'Mening akkauntim',
    'header.profile': 'Profil',
    'header.adminPanel': 'Admin panel',
    'header.tariff': 'Tarif',
    'header.extendTariff': 'Tarif rejani yangilash',
    'header.language': 'Til',
    'header.logout': 'Chiqish',

    'support.title': "Qo'llab-quvvatlash markazi",
    'support.subtitle': 'PROFiboard bo‘yicha javoblar va murojaat',
    'support.tabHelp': 'Ma\'lumot',
    'support.tabContact': 'Bog‘lanish',
    'support.faqHeading': 'Tez-tez beriladigan savollar',
    'support.contactFormTitle': 'Murojaat yaratish',
    'support.viaTelegramHeading': 'Telegram',
    'support.viaTelegramHint': 'QR-kodni skanerlang yoki chatni ochish uchun rasmni bosing.',
    'support.telegramQrAlt': 'Telegramda aloqa uchun QR-kod',
    'support.fieldSubject': 'Mavzu',
    'support.fieldSubjectPh': 'Savolni qisqacha yozing',
    'support.fieldPriority': 'Ustuvorlik',
    'support.priorityLow': 'Past',
    'support.priorityMedium': 'O‘rta',
    'support.priorityHigh': 'Yuqori',
    'support.priorityCritical': 'Jiddiy',
    'support.fieldCategory': 'Kategoriya',
    'support.catTechnical': 'Texnik muammo',
    'support.catBilling': "To'lov va tarif",
    'support.catFeature': 'Funksiya bo‘yicha taklif',
    'support.catData': "Ma'lumot va hisobotlar",
    'support.catOther': 'Boshqa',
    'support.fieldDescription': 'Tavsif',
    'support.fieldDescriptionPh': 'Muammo yoki savolni batafsil yozing…',
    'support.cancel': 'Bekor qilish',
    'support.submitTicket': 'Yuborish',
    'support.sending': 'Yuborilmoqda…',
    'support.ticketSent': 'Murojaat yuborildi',
    'support.ticketSentDesc': 'Akkauntdagi email bo‘yicha siz bilan bog‘lanamiz.',
    'support.subjectRequired': 'Murojaat mavzusini yozing',
    'support.descriptionRequired': 'Tavsifni yozing',
    'support.ticketError': 'Murojaatni yuborib bo‘lmadi',
    
    // Profile dialog
    'profile.title': 'Profil',
    'profile.accountData': "Hisob ma'lumotlari",
    'profile.name': 'Ism',
    'profile.email': 'Email',
    'profile.phone': 'Telefon raqami',
    'profile.newPassword': 'Parol',
    'profile.newPasswordPlaceholder': "Yangi parol (o'zgartirmaslik uchun bo'sh qoldiring)",
    'profile.passwordMinLength': "kamida 6 ta belgi",
    'profile.showPassword': "Parolni ko'rsatish",
    'profile.hidePassword': "Parolni yashirish",
    'profile.save': 'Saqlash',
    'profile.tariffPlan': 'Tarif rejasi',
    'profile.active': 'Faol',
    'profile.inactive': 'Faol emas',
    'profile.validUntil': 'Amal qilish muddati',
    'profile.daysRemaining': 'Qolgan kunlar',
    
    // Language dialog
    'language.title': 'Tilni tanlash',
    'language.russian': 'Ruscha',
    'language.uzbek': "O'zbekcha",

    // Pricing / Tariff dialog
    'pricing.extendTitle': 'Tarifni uzaytirish',
    'pricing.extendHeroTitle': "Tarifni uzaytiring va PROFiboard bilan biznesingizni rivojlantiring.",
    'pricing.extendHeroSubtitle': "Mos tarifni tanlang va sotuvlaringiz o'sishi uchun aniq tahlil oling.",
    'pricing.extendHeroSubtitlePrefix': "Mos tarifni tanlang va aniq tahlil oling ",
    'pricing.extendHeroSubtitleHighlight': "sotuvlaringiz o'sishi uchun",
    'pricing.expiredTitle': 'Tarif muddati tugadi',
    'pricing.expiredHeroTitle': "Tarif muddati tugadi — PROFiboard'ga kirishni uzaytiring",
    'pricing.chooseTariff': 'Tarifni tanlang',
    'pricing.subscription1Month': '1 oylik obuna',
    'pricing.planStandard': 'Standart',
    'pricing.planBusiness': 'Biznes',
    'pricing.launchPrice': 'Ishga tushirish narxi',
    'pricing.forGrowingBusiness': "O'sib borayotgan biznes uchun",
    'pricing.upTo5Stores': "5 ta do'kongacha",
    'pricing.upTo10Stores': "10 ta do'kongacha",
    'pricing.dataAnyPeriod': "Yil boshidan ma'lumotlar",
    'pricing.allFeatures': 'Xizmatning barcha funksiyalari',
    'pricing.perMonth': "so'm / oy",
    'pricing.selectTariff': 'Tarifni tanlash',
    'pricing.limitedOffer': 'CHEKLANGAN TAKLIF',
    'pricing.onePlusOne': '1+1 oy bepul!',
    'pricing.onePlusOnePrefix': '1+1 oy ',
    'pricing.onePlusOneHighlight': 'bepul!',
    'pricing.onePlusOneDesc': "Birinchi oyni to'lang va ikkinchi oyni bepul oling.",
    'pricing.onePlusOneDescPrefix': "Birinchi oyni to'lang va ",
    'pricing.onePlusOneDescHighlight': 'ikkinchi oyni bepul oling.',
    'pricing.promoTelegram': 'Telegram kanalimizga obuna bo\'ling',
    'pricing.promoTelegramBold': "Obuna bo'ling",
    'pricing.promoTelegramRest': 'Telegram kanalimizga',
    'pricing.promoTelegramHint': 'tezkor javoblar va birinchi navbatda yordam',
    'pricing.promoFeedback': 'Xizmat haqida fikr bildiring',
    'pricing.promoFeedbackBold': 'Fikr bildiring',
    'pricing.promoFeedbackRest': 'xizmat haqida',
    'pricing.promoParticipationTitle': 'Ishtirokchilar uchun:',
    'pricing.promoFeedbackHint': "yaxshilanishlar taklif qiling va aynan sizga kerakli xizmatni oling",
    'pricing.select': "Tanlash",
    'pricing.sum': "so'm",
    'pricing.month1': '1 oy',
    'pricing.month3': '3 oy',
    'pricing.month6': '6 oy',
    'pricing.year1': '1 yil',
    'pricing.savings': 'Tejash',
    'pricing.popular': 'Mashhur',
    'pricing.tryFree': "Bepul sinab ko'ring",
    'pricing.tryFreeDesc': "To'lovsiz 10 kun to'liq kirish",
    'pricing.startFree': "Bepul boshlash",
    'pricing.cancelAnytime': "Obunani istalgan vaqtda bekor qilish mumkin",
    'pricing.paymentTitle': "Tarif to'lovi",
    'pricing.qrPlaceholderTitle': 'QR-kod uchun joy',
    'pricing.qrPlaceholderHint': "To'lov uchun QR-kodni shu yerga joylashtiring",
    'pricing.paymentNoticeLine1': "Hozircha to'lov faqat QR-kod orqali mavjud.",
    'pricing.paymentNoticeLine2': "Yaqin orada xizmatga boshqa to'lov usullari ham qo'shiladi.",
    'pricing.howToPayTitle': "Qanday to'lash kerak:",
    'pricing.stepOpenAppLine1': "To'lov ilovasini oching:",
    'pricing.stepOpenAppLine2': "Payme, Click yoki bankingiz ilovasi.",
    'pricing.stepScanQr': 'QR-kodni skaner qiling.',
    'pricing.stepEnterAmount': "Tanlangan tarifga mos summani kiriting:",
    'pricing.month5Price': "Month 5 — 190 000 so'm",
    'pricing.month10Price': "Month 10 — 280 000 so'm",
    'pricing.stepScreenshot': "To'lov tasdig'i skrinshotini oling.",
    'pricing.stepSendTelegramLine1': "To'lov skrinshotini va servisda ro'yxatdan o'tishda ko'rsatilgan telefon raqamini (yoki pochtani) PROFiboard Telegram guruhiga yuboring ",
    'pricing.stepSendTelegramLine2': "(«Telegramga o'tish» tugmasi, o'tish uchun QR-kodli oyna ochiladi).",
    'pricing.importantTitle': 'Muhim:',
    'pricing.importantText': "Tanlangan tarifga kirish to'lov tasdiqlangandan keyin ochiladi. Bu biroz vaqt olishi mumkin.",
    'pricing.goToTelegram': "Telegramga o'tish",
    'pricing.telegramTitle': 'Chek yuborish kanali',

    // Report upload
    'report.uploadReports': 'Hisobotlarni yuklash',
    'report.sales': 'Savdolar',
    'report.expenses': 'Xarajatlar',
    'report.inventory': 'Qoldiqlar',
    'report.storage': 'Saqlash xizmati',
    
    // Actions
    'action.export': 'Eksport',
    'action.import': 'Import',
    'action.apply': "Qo'llash",
    'action.cancel': 'Bekor qilish',
    'action.close': 'Yopish',
    
    // Common
    'common.from': 'dan',
    'common.to': 'gacha',
    'common.or': 'yoki',
    'common.dataPeriod': "Ma'lumotlar:",
    'common.lastUpdate': 'Yangilandi:',
    'common.nextUpdate': 'Keyingi yangilanish:',
    'common.renewTariffForUpdate': "Ma'lumotlarni yangilash uchun tarifni uzaytiring.",
    'common.total': 'Jami',
    'common.pieces': 'dona',
    'common.sum': "so'm",

    // Summary page
    'summary.pageTitle': 'Mening savdolarim (Savdolarim)',
    'summary.blockSales': 'Savdolar',
    'summary.blockFinances': 'Moliya',
    'summary.blockExpenses': 'Xarajatlar',
    'summary.blockWarehouse': 'UZUM OMBORI (FBO)',
    'summary.blockWarehouseFbs': 'Virtual ombor (FBS)',
    'summary.blockUzumServices': 'Xizmatlar',
    'summary.sales.orders': 'Buyurtmalar',
    'summary.sales.ordersTooltip': 'Tanlangan davr uchun jami buyurtmalar soni.',
    'summary.sales.processing': "Qayta ishlanmoqda",
    'summary.sales.processingTooltip': "To'lov kutilayotgan buyurtmalar.",
    'summary.sales.completed': 'Sotib olishlar',
    'summary.sales.completedTooltip': "Mijoz olib ketgan va 10 kun o'tgan buyurtmalar.",
    'summary.sales.returns': 'Qaytarishlar',
    'summary.sales.returnsTooltip': "Mijoz qaytagan yoki bekor qilgan buyurtmalar.",
    'summary.sales.returnRate': 'Qaytarishlar foizi',
    'summary.sales.returnRateTooltip': "Bekor qilingan buyurtmalarning tasdiqlangan buyurtmalarga nisbati, foizda.",
    'summary.sales.averageCheck': "O'rtacha chek",
    'summary.sales.averageCheckTooltip': "Davr uchun o'rtacha buyurtma qiymati.",
    'summary.finance.revenue': 'Tushum',
    'summary.finance.revenueTooltip': 'Tovarlar sotuvidan olingan jami summa.',
    'summary.finance.expenses': 'Xarajatlar',
    'summary.finance.expensesTooltip': 'Ushbu yorliqdagi «Xarajatlar» blokidagi barcha ko\'rsatkichlar yig\'indisi.',
    'summary.finance.profit': 'Foyda',
    'summary.finance.profitTooltip': 'Daromad – Xarajatlar.',
    'summary.finance.salesProfitability': 'Savdo rentabellik darajasi',
    'summary.finance.salesProfitabilityTooltip': '(Foyda / Daromad) × 100. Daromadning qaysi qismi foyda ekanini ko\'rsatadi.',
    'summary.finance.roi': 'Investitsiya rentabelligi',
    'summary.finance.roiTooltip': '(Foyda / tovarlar tannarxi) × 100. Pul qo\'yilmalarning qanchalik foydali ekanini ko\'rsatadi.',
    'summary.finance.revenueTrend': 'Tushum oshisi',
    'summary.finance.revenueTrendTooltip': 'Tanlangan joriy davr daromadining oldingi o\'xshash davr daromadi bilan solishtiruvi.',
    'summary.finance.lostRevenue': 'Tushum kamayishi',
    'summary.finance.lostRevenueTooltip': 'Omborda tovar yo\'qligi tufayli davr uchun potentsial daromad yo\'qotishi = (tovarsiz kunlar) × (kunlik o\'rtacha daromad) barcha tovarlar uchun.',
    'summary.expense.commissionUzum': 'UZUM komissiyasi',
    'summary.expense.logisticsUzum': 'UZUM logistikasi',
    'summary.expense.productCost': 'Tovar tannarxi',
    'summary.expense.productCostEditTooltip': 'Uzum kabinetidagi tannarx. Aktual tannarxni kiriting.',
    'summary.expense.taxes': 'Soliqlar',
    'summary.expense.taxesTooltip': 'Soliq stavkasini kiriting va Enter tugmasini bosing.',
    'summary.expense.extraExpenses': 'Qo\'shimcha xarajatlar',
    'summary.expense.extraExpensesTooltip': '"Qo\'shimcha xarajatlar" yorlig\'ida ko\'rsatilgan xarajatlar.',
    'summary.uzum.storage': 'UZUM saqlash',
    'summary.uzum.storageTooltip': 'Tanlangan davr uchun tovarlarni saqlash uchun to\'lov.',
    'summary.uzum.ads': 'UZUM reklama',
    'summary.uzum.adsTooltip': 'Tanlangan davr uchun marketing kampaniyalari (BUST top, Buyurtmalarni ko‘paytirish, Biriktirilgan sharh) qiymati.',
    'summary.uzum.fines': 'UZUM jarimalar',
    'summary.uzum.finesTooltip': 'Tanlangan davr uchun undirilgan jarimalar.',
    'summary.warehouse.stock': 'Tovarlar ombori',
    'summary.warehouse.stockTooltip': 'UZUM omborida FBO bo\'yicha sotuv uchun saqlanayotgan tovarlar soni.',
    'summary.warehouse.fbsStockTooltip': 'FBS bo\'yicha sotuv uchun o\'z omboringizdagi tovarlar soni.',
    'summary.warehouse.cost': 'Tovar tannarxi',
    'summary.warehouse.retailPrice': 'Chakana narx',
    'summary.warehouse.retailPriceTooltip': 'UZUM omboridagi tovarlarning bozor narxlari bo\'yicha sotilgandagi qiymati.',
    'summary.weeklyInsights.title': 'Oxirgi 7 kundagi biznesingiz',
    'summary.weeklyInsights.collapse': 'Blokni yig‘ish',
    'summary.weeklyInsights.expand': 'Blokni ochish',
    'summary.weeklyInsights.storagePrefix': 'Saqlash xarajatlari ',
    'summary.weeklyInsights.storageChange': '{verb} {percent} ga',
    'summary.weeklyInsights.storageSuffix': ' ({amount} sum)',
    'summary.weeklyInsights.storageIncreased': 'oshdi',
    'summary.weeklyInsights.storageDecreased': 'kamaydi',
    'summary.weeklyInsights.minProfitBeforeName': 'Tovar ',
    'summary.weeklyInsights.minProfitAfterName': ' eng kam foyda keltirdi → ',
    'summary.weeklyInsights.maxProfitBeforeName': 'Tovar ',
    'summary.weeklyInsights.maxProfitAfterName': ' eng ko\'p foyda keltirdi → ',
    'summary.weeklyInsights.emptyIntroLink': 'API ulang',
    'summary.weeklyInsights.emptyIntroSuffix': ' Uzum shaxsiy kabinetidan va biz ko‘rsatamiz:',
    'summary.weeklyInsights.emptyBullet1': 'qaysi tovarlar eng ko‘p foyda keltiradi',
    'summary.weeklyInsights.emptyBullet2': 'qayerda xarajatlar va saqlash o‘sadi',
    'summary.weeklyInsights.emptyBullet3': 'qaysi pozitsiyalar zarar keltiradi',
    'summary.weeklyInsights.emptyBullet4': 'savdolar va foyda qanday o‘zgaradi',
    'filter.allStores': 'Barcha savdo dokonlar',
    'filter.lockedShop': 'Pullik tarifda mavjud',
    'trialShop.title': 'Ko‘rish uchun do‘konni tanlang',
    'trialShop.description': 'Trial tarifida bitta do‘kon bo‘yicha batafsil analitika mavjud',
    'trialShop.confirm': 'Davom etish',
    'trialShop.saving': 'Saqlanmoqda…',
    'trialShop.loadingShops': 'Do‘konlar ro‘yxati yuklanmoqda…',
    'trialShop.noShopsYet': 'Do‘konlar hali yuklanmagan. Ma’lumotlar sinxronizatsiyasi tugashini kuting.',
    'filter.quickPeriod': 'Tezkor davr',
    'filter.from': 'Dan',
    'filter.to': 'Gacha',
    'filter.apply': 'Qo\'llash',
    'filter.reset': 'Tozalash',
    'filter.viewDay': 'Kunlik',
    'filter.viewWeek': 'Haftalik',
    'filter.viewMonth': 'Oylik',
    'filter.noSellsData': 'sells-report ma\'lumotlari yo\'q',
    'filter.dateErrorOrder': '"Dan" sanasi "Gacha"dan keyin bo\'lishi mumkin emas',
    'filter.dateErrorRange': 'Ma\'lumotlar oralig\'ida sanalarni tanlang',
    'tabs.expensesExtra': "Qo'shimcha xarajatlar",
    'tabs.shipmentLabel': 'Yuklab jo\'natish',
    'tabs.monthly': 'Oylik',
    'tabs.cogs': 'Tannarx',

    // COGS tab
    'cogs.lkUzum': 'Tannarx (Uzum)',
    'cogs.lkUzumLine1': 'Tannarx',
    'cogs.lkUzumLine2': '(Uzum)',
    'cogs.actual': 'Tannarx (aktual)',
    'cogs.actualLine1': 'Tannarx',
    'cogs.actualLine2': '(aktual)',
    'cogs.unitMargin': 'Savdo ustamasi',
    'cogs.calculation': 'Ma\'lumotlar bo\'yicha hisoblash',
    'cogs.calculationLine1': 'Hisoblash',
    'cogs.calculationLine2': 'ma\'lumotlar bo\'yicha',
    'cogs.date': 'Oxirgi o\'zgarish sanasi',
    'cogs.dateLine1': 'Oxirgi o\'zgarish',
    'cogs.dateLine2': 'sanasi',
    'cogs.actions': 'Amallar',
    'cogs.sourceUzum': 'Uzum',
    'cogs.sourceProfiboard': 'Profiboard',
    'cogs.edit': 'Tahrirlash',
    'cogs.editTitle': 'Aktual tannarx',
    'cogs.effectiveFrom': 'Boshlanish sanasi',
    'cogs.effectiveFromRequired': 'Boshlanish sanasini kiriting',
    'cogs.firstSaleDate': 'Birinchi sotuv sanasi',
    'cogs.history': 'Tarix',
    'cogs.historyTitle': 'Davr bo\'yicha tannarx',
    'cogs.historyEmpty': 'Sotuv va tannarx ma\'lumotlari yo\'q',
    'cogs.historyPeriod': 'Davr',
    'cogs.historyCogs': 'Tannarx',
    'cogs.historyDelete': 'Davrni o\'chirish',
    'cogs.historyDeleted': 'Davr o\'chirildi',
    'cogs.historyDeleteError': 'Davrni o\'chirib bo\'lmadi',
    'cogs.actualPlaceholder': 'Tannarxni kiriting',
    'cogs.loading': 'Yuklanmoqda…',
    'cogs.loadError': 'Tannarxni yuklab bo\'lmadi',
    'cogs.empty': 'Mahsulotlar yo\'q. Hisobotlarni yuklang.',
    'cogs.saved': 'Tannarx saqlandi',
    'cogs.saveError': 'Saqlab bo\'lmadi',
    'cogs.saving': 'Saqlanmoqda…',
    'cogs.invalidValue': 'To\'g\'ri summani kiriting',
    'cogs.downloadTemplate': 'Shablonni yuklab olish',
    'cogs.templateProducts': 'Tovarlar shabloni',
    'cogs.templateProductsHint': 'Tannarxni to\'ldiring.',
    'cogs.templateEmpty': 'Bo\'sh shablon',
    'cogs.templateEmptyHint': 'Shtrixkod va tannarx.',
    'cogs.uploadTemplate': 'Shablonni yuklash',
    'cogs.uploadLine1': 'Yuklash',
    'cogs.uploadLine2': 'Tanlangan shablon',
    'cogs.templateUploading': 'Yuklanmoqda…',
    'cogs.templateUploaded': 'Yuklangan qatorlar: {count}',
    'cogs.templateUploadedNone': 'Yuklash uchun qatorlar yo\'q. Shablonda tannarxni to\'ldiring.',
    'cogs.templateDownloadError': 'Shablonni yuklab bo\'lmadi',
    'cogs.templateUploadError': 'Shablonni yuklab bo\'lmadi',
    'cogs.templateEffectiveFromTitle': 'Tannarx qo\'llanish sanasi',
    'cogs.templateEffectiveFromHint': 'Yuklanayotgan tannarx shu sanadan boshlab amal qiladi.',
    'cogs.templateAppliedTitle': 'Tannarx qo\'llanildi',
    'cogs.templateAppliedMessage': 'Yuklangan qatorlar: {count}. Tannarx {date} sanasidan qo\'llanildi.',
    'cogs.templateAppliedOk': 'Tushundim',
    'cogs.metricProducts': 'Tovarlar',
    'cogs.metricWithoutCogs': 'Tannarxsiz',
    'cogs.metricProfiboard': 'Hisoblash LK Profiboard',
    'chart.salesByDay': 'Kunlik savdo',
    'chart.noData': 'Hisobotlarni yuklang',
    'header.loggedOut': 'Tizimdan chiqdingiz',
    'header.seller': 'Sotuvchi',
    'header.settings': 'Sozlamalar',
    'header.tariffs': 'Tariflar',

    'chart.ordersPcs': 'Buyurtmalar, dona',
    'chart.revenueMlnSum': 'Daromad, mln so\'m',
    'chart.addComment': 'Izoh qo\'shish',
    'chart.date': 'Sana',
    'chart.selectDate': 'Sanani tanlang',
    'chart.comment': 'Izoh',
    'chart.done': 'Tayyor',
    'chart.delete': 'O\'chirish',
    'chart.reallyOrders': 'haqiqiy',
    'chart.costsThousandSum': "Xarajatlar, ming so'm",
    'progress.mln': 'mln',
    'progress.billion': 'mlrd',
    'progress.thousand': 'ming',

    'product.products': 'Tovarlar (mahsulotlar)',
    'product.productTitle': 'Tovar',
    'product.name': 'Nomi',
    'product.productType': 'Tovar turi',
    'product.productId': 'Tovar Idsi',
    'product.ratingPrefix': 'reyting',
    'product.comment': 'Izoh',
    'product.commentPlaceholder': 'Mahsulotga izoh qoldiring...',
    'product.saving': 'Saqlanmoqda...',
    'product.save': 'Saqlash',
    'product.saveCommentError': 'Izohni saqlashda xato: {0}',
    'product.params': 'Tovar parametrlari',
    'product.orders': 'Buyurtmalar',
    'product.stock': 'Qoldiqlar',
    'product.stockFbo': 'Qoldiqlar (FBO)',
    'product.stockFbs': 'Qoldiqlar (FBS)',
    'product.sizeGroup': 'Gabarit guruhi',
    'product.barcode': 'Shtrixkod',
    'product.storage': 'Saqlash xizmati',
    'product.storageDaySum': 'kun/so\'m',
    'product.total': 'Jami',
    'product.noVariants': 'Mahsulot variantlari yo\'q',
    'product.marginality': 'Umumiy daromadning marginalligi',
    'product.revenueShare': 'Umumiy tushumdan ulushi',
    'product.selectPeriod': 'Sana filtrida davrni tanlang',

    'daily.chartTitle': 'Buyurtmalar va savdo jadvali',
    'daily.dataByDay': 'Kundalik ma\'lumotlar',
    'daily.loading': 'Yuklanmoqda...',
    'daily.loadError': 'Ma\'lumotlarni yuklashda xato',
    'daily.noDataPeriod': 'Hisobotlarni yuklang',
    'daily.date': 'Sana',
    'daily.orders': 'Buyurtmalar',
    'daily.buys': 'Sotib olishlar',
    'daily.returns': 'Qaytarishlar',
    'daily.revenue': 'Tushum',
    'daily.commission': 'Komissiya',
    'daily.logistics': 'Logistika',
    'daily.storage': 'Saqlash',
    'daily.ads': 'Reklama',
    'daily.penalties': 'Jarimalar',
    'daily.cogs': 'Tannarx',
    'daily.tax': 'Soliq',
    'daily.profitNet': 'Sof foyda',
    'daily.granularityDay': 'Kun',
    'daily.granularityWeek': 'Hafta',
    'daily.granularityMonth': 'Oy',
    'daily.exportXLSX': 'XLSX ga yuklash',
    'daily.exportedRows': '{0} qator yuklandi',
    'daily.exportError': 'Yuklashda xato yuz berdi',

    'monthly.totalSold': 'Jami sotilgan',
    'monthly.revenue': 'Tushum',
    'monthly.cost': 'Tannarx',
    'monthly.commission': 'Komissiya miqdori',
    'monthly.logistics': 'Logistika xizmatlari',
    'monthly.storage': 'Saqlash xizmati',
    'monthly.ads': 'Reklama',
    'monthly.fines': 'Jarimalar',
    'monthly.tax': 'Soliq',
    'monthly.extraExpenses': 'Qo\'shimcha xarajatlar',
    'monthly.netProfit': 'Sof foyda',
    'monthly.title': 'Oy bo\'yicha moliyaviy ko\'rsatkichlar',
    'monthly.year': 'Yil',
    'monthly.indicator': 'Ko\'rsatkich',

    'table.productName': 'Tovar nomi',
    'table.turnover': 'Aylanma',
    'table.sizeGroup': 'O\'lchamlar guruhi',
    'table.storagePerDay': 'Saqlash kun/so\'m',
    'table.shop': 'Savdo do\'kon',
    'table.abcOrders': 'ABC buyurtmalar',
    'table.abcProfit': 'ABC foyda',
    'table.abcRevenue': 'ABC daromad',
    'table.noDataProducts': 'Hisobotlarni yuklang',

    'report.salesReport': 'Sotuvlar bo\'yicha hisoboti',
    'report.expensesReport': 'Xizmatlar bo\'yicha hisoboti',
    'report.storageReport': 'Saqlash hisoboti',
    'report.inventoryOld': 'Qoldiqlar (eski format)',

    'expense.date': 'Sana',
    'expense.save': 'Saqlash',
    'expense.add': 'Qo\'shish',
    'expense.type': 'Turi',
    'expense.amount': 'Miqdor',
    'expense.actions': 'Amallar',
    'expense.loading': 'Yuklanmoqda...',
    'expense.noExpensesAdded': 'Xarajatlarni qo\'shing',
    'expense.editDesc': 'Xarajat ma\'lumotlarini o\'zgartiring',
    'expense.addDesc': 'Yangi xarajatlar qo\'shish uchun shaklni to\'ldiring',
    'expense.selectDate': 'Sanani tanlang',

    'report.uploadButton': 'Hisobotlarni yuklash',
    'report.uploadTitle': 'UZUM hisobotlarini yuklash',
    'report.uploadDialogMainTitle': 'Tahlil uchun zarur bo‘lgan Uzumning 4 ta asosiy hisoboti.',
    'report.guidedHeroTitle': '2 daqiqada savdo va foyda tahlilini oling',
    'report.guidedHeroSubtitle':
      'Uzum shaxsiy kabinetidan 4 ta hisobotni yuklang — nima foyda keltirishi va biznesingizni pastga tortishini ko‘rsatamiz.',
    'report.guidedBenefitsHeading': 'Yuklashdan keyin nima olasiz',
    'report.guidedBenefit1Title': 'Foyda va haqiqiy',
    'report.guidedBenefit1Desc': 'kunlar bo‘yicha ko‘rsatkichlar',
    'report.guidedBenefit2Title': 'Eng foydali',
    'report.guidedBenefit2Desc': 'va zararli tovarlar',
    'report.guidedBenefit3Title': 'Barcha xarajatlar',
    'report.guidedBenefit3Desc': 'va Uzum komissiyalari',
    'report.guidedBenefit4Title': 'Qoldiqlar va saqlash',
    'report.guidedBenefit4Desc': 'tovarlari',
    'report.guidedBenefit5Title': 'Trendlar va dinamika',
    'report.guidedBenefit5Desc': 'savdosi',
    'report.guidedDataSafetyTitle': 'Ma’lumotlaringiz xavfsiz',
    'report.guidedDataSafetyBody':
      'Uchinchi shaxslarga bermaymiz. Istalgan vaqtda o‘chirib tashlashingiz mumkin.',
    'report.guidedStep1Title': 'Uzum SKdan 4 ta hisobotni yuklab oling',
    'report.guidedStep1Body':
      '1. 4 ta hisobotni shakllantiring: Savdolar, Xizmatlar, Qoldiqlar (eski format), Saqlash.\n2. XLSX formatida kompyuterga saqlang.',
    'report.guidedStep1Footnote':
      'Hisobotlar barchasi bir davr uchun bo‘lishi kerak. Yil boshidan boshlab yuklashni tavsiya qilamiz.',
    'report.guidedStep2Title': 'PROFiboard’ga 4 ta hisobotni yuklang',
    'report.guidedStep2Body':
      '1. PROFiboard sarlavhasidagi «Hisobotlarni yuklash» tugmasini bosing.\n2. Fayllarni sudrab tashlang yoki yuklash oynasini bosing.',
    'report.guidedSocialProofBold': 'Sotuvchilarning 98%',
    'report.guidedSocialProofRest':
      'hisobotlarni birinchi marta yuklaganidan keyin 2 daqiqada tahlil oladi.',
    'report.guidedDemoHeading': 'Hozir yuklamoqchi emasmisiz?',
    'report.guidedDemoSubtitle': 'Haqiqiy ma’lumotlar bilan demo-dashbordni ko‘ring.',
    'report.guidedDemoButton': 'Demoni ko‘rish',
    'report.guidedDemoPreviewAlt': 'PROFiboard demo-dashbord ko‘rinishi',
    'report.guidedTelegramHelpTitle': 'Birinchi yuklashda yordam kerakmi?',
    'report.guidedTelegramHelpBody':
      'Telegramda 5 daqiqa ichida javob beramiz va qadam-baqadam yordam beramiz.',
    'report.uploadStepsHeading': 'Hisobotlarni SKda qanday olish va PROFiboardga qanday yuklash',
    'report.watchImportVideo': 'Videoni tomosha qilish',
    'report.watchImportVideoGuided': 'Videoni tomosha qilish (~2 daqiqa)',
    'report.importVideoModalTitle': 'Hisobotlarni import qilish',
    'report.firstUploadHelp': 'Birinchi yuklash bo‘yicha yordam kerak bo‘lsa — Telegram orqali murojaat qiling, yordam beramiz.',
    'report.openTelegram': 'Telegramni ochish',
    'report.uploadFilesSectionTitle': 'Fayllarni yuklash',
    'report.howItWorks': 'Bu qanday ishlaydi?',
    'report.bullet1': 'UZUM shaxsiy kabinetidan XLSX hisobotlarni yuklang',
    'report.bullet2': "Tizim hisobot turini avtomatik ravishda taniydi va ma'lumotlarni import qiladi",
    'report.bullet3': 'MUHIM: Barcha hisobotlar bir davr uchun bo\'lishi kerak',
    'report.dragOrClick': 'Fayllarni sudrab tashlang yoki bosing',
    'report.close': 'Yopish',
    'report.stepImageZoomAria': 'Rasmni kattalashtirish',
    'report.uploadFilesButton': 'Fayllarni yuklash',
    'report.upload': 'Yuklash',
    'report.lastUpload': 'Oxirgi yuklash',
    'report.uploadingReports': 'Hisobotlar yuklanmoqda...',
    'report.storeLimitExceeded': 'Do\'konlar bo\'yicha ruxsat etilgan chegaradan oshish',
    'storeLimit.title': 'Do\'konlar limiti tugadi',
    'storeLimit.description': 'Sizning {currentTariff} tarifingiz {max} tagacha do\'kon ulash imkonini beradi. Yangi do\'kon qo\'shish uchun tarifni yangilang.',
    'storeLimit.connected': 'Ulangan: {current} / {max}',
    'storeLimit.upgradeButton': '{nextTariff} tarifiga o\'tish',
    'storeLimit.contactSupport': 'Do\'konlarni ko\'paytirish uchun qo\'llab-quvvatlash xizmatiga murojaat qiling',
    'report.importedRows': 'Import qilindi: {0} qator',
    'report.onlyLeftout': 'Faqat left-out-report_old qabul qilinadi',
    'report.productAdLink': 'Mahsulotlar va reklama aloqasi',
    'report.adLinkDesc': 'Har bir mahsulotni reklama xarajatlarini aniq hisoblash uchun reklama kampaniyalari ID sini kiriting.',
    'report.enterAdId': 'Reklama ID sini kiriting',
    'report.adId': 'Reklama ID',
    'report.loadError': 'Ma\'lumotlarni yuklashda xato',
    'shipment.noDataHint': 'Hisobotlarni yuklang',
    'search.byNameArticle': 'Nomi, artikuli bo\'yicha qidiruv...',
    'products.enterCogs': 'Tannarxni kiritish',
    'products.groupByCards': 'Kartalar kesimida guruhlash',
    'products.loading': 'Tovarlar yuklanmoqda…',
    'products.updating': 'Ma’lumotlar yangilanmoqda…',
    'products.loadError': 'Tovarlarni yuklab bo‘lmadi. Sahifani yangilab ko‘ring.',
    'expense.howItWorks': 'Bu qanday ishlaydi?',
    'howItWorks.triggerLabel': 'Bu qanday ishlaydi?',
    'howItWorks.triggerTooltip': 'Barcha bo‘limlar bo‘yicha maslahat',
    'howItWorks.triggerAria': 'Barcha bo‘limlar bo‘yicha maslahatni ochish',
    'howItWorks.panelTitle': '«{tab}» bo‘limi qanday ishlaydi',
    'expense.howItWorks1': 'Bu yerda hisobotlar yoki API orqali uzatilmaydigan qo\'shimcha xarajatlarni qo\'lda qo\'shishingiz mumkin',
    'expense.howItWorks2': 'Misol: o\'zini o\'zi xarid qilish, maosh, tashqi reklama, o\'z logistikasi va boshqalar',
    'expense.howItWorks3': 'Xarajatlar tanlangan sana va do\'kon/mahsulot uchun barcha moliyaviy hisobotlarda hisobga olinadi',
    'expense.howItWorks4': 'Ko\'rsatilmasa — xarajatlar oylik hisobotga umuman qo\'shiladi',
    'howItWorks.summary.item1': 'Vkladkada asosiy metrikalar bo‘yicha batafsil ma’lumotlar ko‘rsatilgan: Sovdolar, Moliya, Xarajatlar, Ombor.',
    'howItWorks.summary.itemCogsBefore': 'Foydani aniq hisoblash uchun ',
    'howItWorks.summary.itemCogsLink': 'aktual tannarxni ko‘rsating',
    'howItWorks.summary.itemCogsAfter': ' mahsulotlaringiz uchun.',
    'howItWorks.summary.item2Before': 'Belgisi',
    'howItWorks.summary.item2After': 'har bir ko‘rsatkich haqida qisqacha ma’lumot beradi.',
    'howItWorks.summary.item3': '«Oxirgi 7 kundagi biznesingiz» bloki foyda va saqlash bo‘yicha tezkor insaytlarni ko‘rsatadi.',
    'howItWorks.summary.item4': 'O‘ng tomonda filtrlar joylashgan, u yerda ko‘rmoqchi bo‘lgan vaqt oralig‘ini va do‘konni tanlashingiz mumkin.',
    'howItWorks.daily.item1': 'Grafikda kerakli metrikani tanlang (Buyurtmalar, Qaytarishlar, Tushum va h.k.) va uning davr ichidagi o‘zgarishini ko‘ring.',
    'howItWorks.daily.item2': 'Davr va guruhlash bo‘yicha filtrlaridan foydalaning: kunlik, haftalar yoki oylar bo‘yicha — grafik shunga mos ravishda qayta tuziladi.',
    'howItWorks.daily.item3': 'Grafik ostidagi jadvalda barcha metrikalar bo‘yicha ma’lumotlarni tartiblashingiz mumkin; ma’lumotlarni Excel formatida yuklab olish ham mumkin.',
    'howItWorks.products.item1': 'O‘ng tomondagi asosiy filtrlardan foydalanib, davr yoki do‘konni tanlang.',
    'howItWorks.products.item2': 'Bir xil turdagi barcha mahsulotlarni birlashtirish uchun «Kartalar kesimida guruhlash» funksiyasidan foydalaning.',
    'howItWorks.products.item3': 'Mahsulot ustiga bosing — u bo‘yicha ma’lumotlarni ochishingiz va kerak bo‘lsa, izoh qoldirishingiz mumkin.',
    'howItWorks.products.item4': 'Jadvaldagi ma’lumotlarni tartiblash uchun ustun sarlavhalaridagi saralash belgisidan foydalaning.',
    'howItWorks.shipment.item1': 'O‘ng tomondagi asosiy filtrlardan foydalanib, do‘konni tanlang.',
    'howItWorks.shipment.item2': 'Tovarni UZUM omboriga (FBO) necha kundan keyin jo‘natishni rejalashtirayotganingizni belgilang. Servis pullik saqlashga tushib qolmasligi uchun qancha tovar olib kelish kerakligini hisoblab beradi.',
    'howItWorks.shipment.item3': 'Jo‘natish uchun kerak bo‘lgan tovarlaringiz ro‘yxatini Excel formatida yuklab olishingiz mumkin.',
    'howItWorks.monthly.item1': 'Ushbu bo‘limda har oy uchun barcha do‘konlaringiz bo‘yicha ma’lumotlar ko‘rsatilgan.',
    'howItWorks.monthly.item2': 'Qo‘shimcha xarajatlarda «qo‘shimcha xarajatlar» bo‘limida kiritgan barcha xarajatlaringiz ko‘rsatiladi.',
    'howItWorks.monthly.item3': 'Soliq «Hisobotlar» bo‘limida siz ko‘rsatgan foiz asosida hisoblanadi.',
    'howItWorks.cogs.item1': 'Foydani aniq hisoblash uchun mahsulotlaringizning aktual tannarxini ko\'rsatish muhim. Biz birinchi navbatda PROFIboard dagi tannarx ma\'lumotlarini ishlatamiz. Agar u yerda to\'ldirilmagan bo\'lsa, UZUM sotuvchi kabineti dagi ma\'lumotlar olinadi.',
    'howItWorks.cogs.item2': 'Har bir mahsulot uchun ma\'lumotni alohida o\'zgartirishingiz mumkin. Yoki shablonni yuklab olib, to\'ldirib, hamma ma\'lumotni bir yo\'la yuklashingiz mumkin.',
    'howItWorks.cogs.item3': 'Muhim! Agar yil davomida mahsulotlaringiz tannarxi o\'zgargan bo\'lsa, har bir davr uchun alohida tannarxni ko\'rsatishingiz mumkin. Shunda ma\'lumotlar iloji boricha aniq bo\'ladi.',
    'howItWorks.cogs.item4': 'Agar tannarxni birinchi marta kiritayotgan bo\'lsangiz, sanani yil boshidan (1.01) qo\'ying.',
    'expense.addExpense': 'Xarajatlar qo\'shish',
    'expense.editExpense': 'Xarajatni tahrirlash',
    'expense.typeLabel': 'Xarajatlar turi',
    'expense.selectType': 'Turni tanlang',
    'expense.notSelected': 'Tanlanmagan',
    'expense.notSelectedItem': 'Tanlanmagan',
    'expense.selectShopOptional': 'Do\'konni tanlang (ixtiyoriy)',
    'expense.selectNameOptional': 'Nomini tanlang (ixtiyoriy)',
    'expense.noShopsAvailable': 'Do\'konlar mavjud emas (seller-storage yuklang)',
    'expense.noNamesAvailable': 'Nomlar mavjud emas (left-out-report_old yuklang)',
    'expense.commentOptional': 'Izoh qo\'shish (ixtiyoriy)',
    'expense.typeSelfBuy': 'O\'zini o\'zi xarid',
    'expense.typeSalary': 'Maosh',
    'expense.typeExternalAds': 'Tashqi reklama',
    'expense.typeOwnLogistics': 'O\'z logistikasi',
    'expense.typePackaging': 'Qadoqlash',
    'expense.typeRent': 'Ijara',
    'expense.typeOther': 'Boshqa',
    'shipment.daysUntil': 'Uzum omboriga yuborishgacha kunlar',
    'shipment.daysCount': 'Kunlar soni',
    'shipment.daysDescription': 'Oxirgi hisobot yuklash sanasidan boshlab tovar yuklanishi rejalashtirilgan kunlar sonini kiriting',
    'shipment.considerStock': 'Ombor qoldiqlarini hisobga olish',
    'shipment.yes': 'Ha',
    'shipment.no': 'Yo\'q',
    'shipment.calculate': 'Hisoblash',
    'shipment.calculating': 'Hisoblanmoqda…',
    'shipment.recommendations': 'Yuklab jo\'natish bo\'yicha tavsiyalar',
    'shipment.exportXLSX': 'XLSX ga yuklash',
    'shipment.product': 'Tovar',
    'shipment.article': 'Artikul',
    'shipment.inStock': 'Omborda',
    'shipment.salesPerDay': 'Kunlik savdo',
    'shipment.recommendedQty': 'Tavsiya etilgan miqdor',
    'shipment.plannedToShip': 'Yuklashga rejalashtirilgan',
    'shipment.calculationDone': 'Hisoblash yakunlandi',
    'shipment.exportedRows': '{0} qator yuklandi',
    'shipment.exportError': 'Yuklab olishda xatolik',
    'monthly.jan': 'Yan',
    'monthly.feb': 'Fev',
    'monthly.mar': 'Mar',
    'monthly.apr': 'Apr',
    'monthly.may': 'May',
    'monthly.jun': 'Iyun',
    'monthly.jul': 'Iyul',
    'monthly.aug': 'Avg',
    'monthly.sep': 'Sen',
    'monthly.oct': 'Okt',
    'monthly.nov': 'Noy',
    'monthly.dec': 'Dek',

    'alert.noStockData': 'Hisobotlarni yuklang',
    'alert.stockZero': 'Ombor = 0',
    'alert.stockZeroDesc': 'left-out-report_old ma\'lumotlariga ko\'ra omborda 0. «Ombor» yuklash yoki do\'kon filtrini tekshiring.',
    'alert.stockZeroReasonAll': 'Oxirgi ombor yuklashida (left-out-report_old) «Sotuvda» summa = 0. Ombor/qoldiq faylini tekshiring.',
    'common.snapshot': 'Kesim',
    // Stock daily chart tooltips
    'stockDaily.title': 'Ombordagi qoldiqlar kunlar bo‘yicha',
    'stockDaily.noData': 'Tanlangan davr uchun ombor bo‘yicha maʼlumot yo‘q',
    'stockDaily.orders': 'Buyurtmalar',
    'stockDaily.stock': 'Ombordagi tovarlar',
    'stockDaily.stockAxis': 'Ombordagi tovarlar, dona',
    // Category chart
    'categoryChart.title': 'Toifalar bo‘yicha savdolar',
    'categoryChart.subtitle': 'Oy bo‘yicha eng yaxshi toifalar',
    'categoryChart.tooltipSales': 'Savdolar',
    // Analytics revenue chart
    'analytics.revenueOrdersTitle': 'Daromad va buyurtmalar',
    'analytics.revenueOrdersSubtitle': 'Davr bo‘yicha dinamikasi',
    // Sidebar
    'sidebar.toggle': 'Menyuni yopish/ochish',
    // Admin panel tabs
    'admin.tabs.overview': 'Umumiy ko‘rinish',
    'admin.tabs.uzum': 'API',
    'admin.tabs.uzumUsers': 'API user',
    'admin.tabs.archive': 'Arxiv',
    'admin.uzumSyncLogs.title': 'Uzum API yangilash jurnali',
    'admin.uzumSyncLogs.subtitle': 'Avtomatik va qo‘lda yangilash (06:00 va 18:00, Asia/Tashkent)',
    'admin.uzumSyncLogs.refresh': 'Yangilash',
    'admin.uzumSyncLogs.exportExcel': 'Excel ga yuklash',
    'admin.uzumSyncLogs.exporting': 'Yuklanmoqda…',
    'admin.uzumSyncLogs.exportEmpty': 'Yuklash uchun yozuvlar yo‘q',
    'admin.uzumSyncLogs.exportFailed': 'Excel yuklab bo‘lmadi',
    'admin.uzumSyncLogs.selectAll': 'Hammasini belgilash',
    'admin.uzumSyncLogs.deselectAll': 'Belgilashni olib tashlash',
    'admin.uzumSyncLogs.deleteSelected': 'O‘chirish',
    'admin.uzumSyncLogs.deleting': 'O‘chirilmoqda…',
    'admin.uzumSyncLogs.deleteSuccess': 'O‘chirilgan yozuvlar',
    'admin.uzumSyncLogs.deleteFailed': 'Yozuvlarni o‘chirib bo‘lmadi',
    'admin.uzumSyncLogs.selectRow': 'Qatorni belgilash',
    'admin.uzumSyncLogs.metricActive': 'Active',
    'admin.uzumSyncLogs.metricDays': 'Days',
    'admin.uzumSyncLogs.metricSuccess': 'Success',
    'admin.uzumSyncLogs.metricFailed': 'Failed',
    'admin.uzumSyncLogs.metricSuccessRate': 'Muvaffaqiyat, %',
    'admin.uzumSyncLogs.metricManual': 'Manual',
    'admin.uzumSyncLogs.metricScheduled': 'Scheduled',
    'admin.uzumSyncLogs.userId': 'user_id',
    'admin.uzumSyncLogs.email': 'Email',
    'admin.uzumSyncLogs.startedAt': 'Boshlanish',
    'admin.uzumSyncLogs.finishedAt': 'Tugash',
    'admin.uzumSyncLogs.duration': 'Vaqt',
    'admin.uzumSyncLogs.status': 'Holat',
    'admin.uzumSyncLogs.trigger': 'Manba',
    'admin.uzumSyncLogs.lastSync': 'Oxirgi muvaffaqiyatli sync',
    'admin.uzumSyncLogs.error': 'Xato',
    'admin.uzumSyncLogs.errorDetailTitle': "Xato to'liq matni",
    'admin.uzumSyncLogs.loading': 'Yuklanmoqda…',
    'admin.uzumSyncLogs.empty': 'Yozuvlar yo‘q',
    'admin.uzumSyncLogs.page': 'Sahifa',
    'admin.uzumSyncLogs.prev': 'Orqaga',
    'admin.uzumSyncLogs.next': 'Oldinga',
    'admin.archive.description': 'Uzum kabinetidan qo‘lda hisobot yuklash (XLSX).',
    // Admin subscriptions and tooltips
    'admin.subscriptions.title': 'Obunalar tahlili',
    'admin.subscriptions.revenue': 'Daromad (so\'m)',
    'admin.subscriptions.subscribers': 'Obunachilar',
    'admin.monthly.registrationsHelp': 'Oylik ro‘yxatdan o‘tgan foydalanuvchilar soni',
    'admin.tooltip.disableTenant': 'O‘chirish',
    'admin.tooltip.enableTenant': 'Yoqish',
    'admin.tooltip.extendTrial': 'Sinov muddatini uzaytirish',
    'admin.tooltip.recordPayment': 'To‘lovni qayd etish',
    'admin.tooltip.changePassword': 'Parolni o‘zgartirish / tiklash',
    'admin.tooltip.deleteTenant': 'Akkaunt va maʼlumotlarni o‘chirish',
    'admin.tooltip.uzumSync': 'Uzum API ulanishini yangilash',
  },
};

const APP_LANGUAGE_KEY = 'app-language';

function getStoredLanguage(): Language | null {
  const saved = localStorage.getItem(APP_LANGUAGE_KEY);
  if (saved === 'ru' || saved === 'uz') return saved;
  return null;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>(() => getStoredLanguage() ?? 'ru');
  const initialUserLangApplied = useRef(false);

  // После входа: язык с лендинга (localStorage) важнее старого значения в профиле; синхронизируем в аккаунт
  useEffect(() => {
    if (!user) {
      initialUserLangApplied.current = false;
      return;
    }
    if (initialUserLangApplied.current) return;
    initialUserLangApplied.current = true;

    const stored = getStoredLanguage();
    if (stored) {
      setLanguageState(stored);
      if (user.preferred_language !== stored) {
        apiPatch('/api/auth/me', { preferred_language: stored }).catch(() => {});
      }
      return;
    }

    const pl = user.preferred_language;
    if (pl === 'ru' || pl === 'uz') {
      setLanguageState(pl);
      localStorage.setItem(APP_LANGUAGE_KEY, pl);
    }
  }, [user?.id, user?.preferred_language]);

  useEffect(() => {
    localStorage.setItem(APP_LANGUAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      apiPatch('/api/auth/me', { preferred_language: lang }).catch(() => {
        // при ошибке сетевого запроса язык уже сменён локально
      });
    }
  };

  const t = (key: string): string => {
    const dict = translations[language] as Record<string, string>;
    return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
