import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    'nav.dashboard': 'Дашборд',
    'nav.products': 'Товары',
    'nav.analytics': 'Аналитика',
    'nav.competitors': 'Конкуренты',
    'nav.trends': 'Тренды',
    'nav.reports': 'Отчёты',
    'nav.support': 'Поддержка',
    
    // Tabs
    'tabs.summary': 'Сводка',
    'tabs.products': 'Товары',
    'tabs.daily': 'По дням',
    'tabs.expenses': 'Расходы',
    'tabs.shipment': 'Поставка',
    
    // Filters
    'filter.today': 'Сегодня',
    'filter.yesterday': 'Вчера',
    'filter.week': 'Неделя',
    'filter.month': 'Месяц',
    'filter.year': 'Год',
    'filter.period': 'Период',
    'filter.all': 'Все',
    'filter.excess': 'Избыток',
    'filter.outOfStock': 'Нет на складе',
    'filter.needSupply': 'Нужна поставка',
    
    // KPI Cards
    'kpi.revenue': 'Выручка',
    'kpi.orders': 'Заказы',
    'kpi.returns': 'Возвраты',
    'kpi.profit': 'Прибыль',
    'kpi.marginality': 'Маржинальность',
    'kpi.averageCheck': 'Средний чек',
    
    // Blocks
    'block.finances': 'Финансы',
    'block.expenses': 'Расходы',
    'block.warehouse': 'Склад',
    'block.revenueProgress': 'Накопительная выручка',
    
    // Finance items
    'finance.revenue': 'Выручка',
    'finance.logistics': 'Логистика',
    'finance.commission': 'Комиссия',
    'finance.promoDiscount': 'Скидка по акции',
    'finance.netRevenue': 'Чистая выручка',
    
    // Expense items
    'expense.soldGoodsCost': 'Себест. проданных товаров',
    'expense.logistics': 'Логистика',
    'expense.commission': 'Комиссия',
    'expense.promoDiscount': 'Скидка по акции',
    'expense.advertising': 'Реклама',
    'expense.fines': 'Штрафы',
    'expense.storage': 'Хранение',
    'expense.other': 'Прочее',
    'expense.total': 'Итого расходов',
    
    // Warehouse items
    'warehouse.warehouseStock': 'Себест. товара на складе',
    'warehouse.potentialRevenue': 'Потенциальная выручка',
    'warehouse.potentialProfit': 'Потенциальная прибыль',
    
    // Table headers
    'table.product': 'Товар',
    'table.article': 'Артикул',
    'table.category': 'Категория',
    'table.costPrice': 'Себестоимость',
    'table.price': 'Цена',
    'table.orders': 'Заказы',
    'table.returns': 'Возвраты',
    'table.stock': 'Остаток',
    'table.availability': 'Наличие',
    'table.revenue': 'Выручка',
    'table.profit': 'Прибыль',
    'table.margin': 'Маржа',
    
    // Availability status
    'availability.excess': 'Избыток',
    'availability.outOfStock': 'Нет на складе',
    'availability.needSupply': 'Нужна поставка',
    
    // Header
    'header.search': 'Поиск товаров, категорий...',
    'header.notifications': 'Уведомления',
    'header.allNotifications': 'Все уведомления',
    'header.help': 'Помощь',
    'header.faq': 'Часто задаваемые вопросы',
    'header.videoTutorials': 'Видео-уроки',
    'header.support': 'Поддержка',
    'header.myAccount': 'Мой аккаунт',
    'header.profile': 'Профиль',
    'header.adminPanel': 'Админ-панель',
    'header.tariff': 'Тариф',
    'header.extendTariff': 'Продлить тариф',
    'header.language': 'Язык',
    'header.logout': 'Выйти',
    
    // Profile dialog
    'profile.title': 'Профиль',
    'profile.accountData': 'Данные аккаунта',
    'profile.name': 'Имя',
    'profile.email': 'Email',
    'profile.phone': 'Номер телефона',
    'profile.save': 'Сохранить',
    'profile.tariffPlan': 'Тарифный план',
    'profile.active': 'Активен',
    'profile.validUntil': 'Действует до',
    'profile.daysRemaining': 'Осталось дней',
    
    // Language dialog
    'language.title': 'Выбор языка',
    'language.russian': 'Русский',
    'language.uzbek': 'Узбекский',
    
    // Report upload
    'report.uploadReports': 'Загрузить отчёты',
    'report.sales': 'Продажи',
    'report.expenses': 'Расходы',
    'report.inventory': 'Остатки',
    'report.storage': 'Хранение',
    
    // Actions
    'action.export': 'Экспорт',
    'action.import': 'Импорт',
    'action.apply': 'Применить',
    'action.cancel': 'Отмена',
    'action.close': 'Закрыть',
    
    // Common
    'common.from': 'от',
    'common.to': 'до',
    'common.total': 'Итого',
    'common.pieces': 'шт',
    'common.sum': 'сум',

    // Summary page
    'summary.pageTitle': 'Мои продажи на',
    'summary.blockSales': 'ПРОДАЖИ',
    'summary.blockFinances': 'ФИНАНСЫ',
    'summary.blockExpenses': 'РАСХОДЫ',
    'summary.blockWarehouse': 'СКЛАД',
    'summary.blockUzumServices': 'УСЛУГИ UZUM',
    'summary.sales.orders': 'Заказы',
    'summary.sales.ordersTooltip': 'Общее кол-во заказов за выбранный период.',
    'summary.sales.processing': 'В обработке',
    'summary.sales.processingTooltip': 'Заказы по которым ожидается оплата.',
    'summary.sales.completed': 'Выкупы',
    'summary.sales.completedTooltip': 'Заказы которые клиент забрал, и прошло 10 дней.',
    'summary.sales.returns': 'Возвраты',
    'summary.sales.returnsTooltip': 'Заказы которые клиент вернул или отменил.',
    'summary.sales.returnRate': 'Процент возврата заказов',
    'summary.sales.returnRateTooltip': 'Отношение отменённых заказов к выкупленным заказам, выраженное в процентах.',
    'summary.sales.averageCheck': 'Средний чек',
    'summary.sales.averageCheckTooltip': 'Средняя стоимость заказа за период.',
    'summary.finance.revenue': 'Выручка',
    'summary.finance.revenueTooltip': 'Общая сумма денег, полученная вами от реализации товаров.',
    'summary.finance.expenses': 'Расходы',
    'summary.finance.expensesTooltip': 'Сумма всех расходов, представленных во вкладке «Расходы» (услуги UZUM не учитываются).',
    'summary.finance.profit': 'Прибыль',
    'summary.finance.profitTooltip': 'Выручка – Расходы.',
    'summary.finance.salesProfitability': 'Рентабельность продаж',
    'summary.finance.salesProfitabilityTooltip': '(Прибыль / Выручка) × 100. Показывает, какая часть выручки является прибылью.',
    'summary.finance.roi': 'Окупаемость инвестиций',
    'summary.finance.roiTooltip': '(Прибыль / себестоимость товаров) × 100. Показывает, насколько выгодно вложение денег.',
    'summary.finance.revenueTrend': 'Тренд выручки',
    'summary.finance.revenueTrendTooltip': 'Сравнение выручки за выбранный текущий период с выручкой за аналогичный период ранее.',
    'summary.finance.lostRevenue': 'Упущенная выручка',
    'summary.finance.lostRevenueTooltip': 'Потенциальная потеря выручки за период из-за отсутствия товаров на складе = (кол-во дней без товара) × (средняя выручка за день) для всех товаров.',
    'summary.expense.commissionUzum': 'Комиссия UZUM',
    'summary.expense.logisticsUzum': 'Логистика UZUM',
    'summary.expense.productCost': 'Себест. прод. тов.',
    'summary.expense.taxes': 'Налоги',
    'summary.expense.extraExpenses': 'Доп. расходы',
    'summary.expense.extraExpensesTooltip': 'Расходы, указанные вами во вкладке «Доп. расходы».',
    'summary.uzum.storage': 'Хранение UZUM',
    'summary.uzum.storageTooltip': 'Стоимость платного хранения товаров за выбранный период.',
    'summary.uzum.ads': 'Реклама UZUM',
    'summary.uzum.adsTooltip': 'Стоимость маркетинговых кампаний (БУСТ в топ) за выбранный период.',
    'summary.uzum.fines': 'Штрафы UZUM',
    'summary.uzum.finesTooltip': 'Начисленные штрафы за выбранный период.',
    'summary.warehouse.stock': 'Товаров на складе',
    'summary.warehouse.stockTooltip': 'Кол-во товаров, хранящихся на складе UZUM для продажи по FBO.',
    'summary.warehouse.cost': 'Себест. тов.',
    'summary.warehouse.retailPrice': 'Рознич. цена',
    'summary.warehouse.retailPriceTooltip': 'Стоимость товаров, хранящихся на складе UZUM, при продаже их по ценам маркетплейса.',
    'filter.allStores': 'Все магазины',
    'filter.quickPeriod': 'Быстрый период',
    'filter.from': 'От',
    'filter.to': 'До',
    'filter.apply': 'Применить',
    'filter.reset': 'Сбросить',
    'filter.viewDay': 'По дням',
    'filter.viewWeek': 'По неделям',
    'filter.viewMonth': 'По месяцам',
    'filter.noSellsData': 'Нет данных sells-report',
    'filter.dateErrorOrder': 'Дата «От» не может быть позже «До»',
    'filter.dateErrorRange': 'Выберите даты в диапазоне данных',
    'tabs.expensesExtra': 'Доп. расходы',
    'tabs.shipmentLabel': 'Отгрузка',
    'tabs.monthly': 'По месячно',
    'chart.salesByDay': 'Продажи по дням',
    'chart.noData': 'Нет данных',
    'header.loggedOut': 'Вы вышли из системы',
    'header.seller': 'Продавец',
    'header.settings': 'Настройки',
    'header.tariffs': 'Тарифы',

    // Chart axis & legend
    'chart.ordersPcs': 'Заказы, шт',
    'chart.revenueMlnSum': 'Выручка, млн сум',
    'chart.addComment': 'Добавить комментарий',
    'chart.date': 'Дата',
    'chart.selectDate': 'Выберите дату',
    'chart.comment': 'Комментарий',
    'chart.done': 'Готово',
    'chart.delete': 'Удалить',
    'chart.reallyOrders': 'реально',
    'chart.costsThousandSum': 'Затраты, тыс сум',
    'progress.mln': 'млн',
    'progress.billion': 'млрд',
    'progress.thousand': 'тыс',

    // Product detail
    'product.products': 'Товары',
    'product.productTitle': 'ТОВАР',
    'product.name': 'Название',
    'product.productType': 'Тип товара',
    'product.productId': 'ID товара',
    'product.comment': 'Комментарий',
    'product.commentPlaceholder': 'Оставьте комментарий к товару...',
    'product.saving': 'Сохранение...',
    'product.save': 'Сохранить',
    'product.saveCommentError': 'Ошибка при сохранении комментария: {0}',
    'product.params': 'Параметры товара',
    'product.orders': 'Заказы',
    'product.stock': 'Остатки',
    'product.sizeGroup': 'Габ. группа',
    'product.barcode': 'Штрихкод',
    'product.storage': 'Хранение',
    'product.storageDaySum': 'сут/сум',
    'product.total': 'Всего',
    'product.noVariants': 'Нет вариантов товара',
    'product.marginality': 'Маржинальность',
    'product.revenueShare': 'От общей выручки',
    'product.selectPeriod': 'Выберите период в фильтре дат',

    // Daily view
    'daily.chartTitle': 'График заказов и продаж',
    'daily.dataByDay': 'Данные по дням',
    'daily.loading': 'Загрузка...',
    'daily.loadError': 'Ошибка загрузки данных',
    'daily.noDataPeriod': 'Нет данных за выбранный период',
    'daily.date': 'Дата',
    'daily.orders': 'Заказы',
    'daily.buys': 'Выкупы',
    'daily.returns': 'Возвраты',
    'daily.revenue': 'Выручка',
    'daily.commission': 'Комиссия',
    'daily.logistics': 'Логистика',
    'daily.storage': 'Хранение',
    'daily.ads': 'Реклама',
    'daily.penalties': 'Штрафы',
    'daily.cogs': 'Себестоимость',
    'daily.tax': 'Налог',
    'daily.profitNet': 'Чистая прибыль',
    'daily.granularityDay': 'День',
    'daily.granularityWeek': 'Неделя',
    'daily.granularityMonth': 'Месяц',

    // Monthly table
    'monthly.totalSold': 'Всего продано',
    'monthly.revenue': 'Выручка',
    'monthly.cost': 'Себестоимость',
    'monthly.commission': 'Комиссия',
    'monthly.logistics': 'Логистика',
    'monthly.storage': 'Хранение',
    'monthly.ads': 'Реклама',
    'monthly.fines': 'Штрафы',
    'monthly.tax': 'Налог',
    'monthly.extraExpenses': 'Доп. расходы',
    'monthly.netProfit': 'ЧИСТАЯ ПРИБЫЛЬ',
    'monthly.title': 'Финансовые показатели по месяцам',
    'monthly.year': 'год',
    'monthly.indicator': 'Показатель',

    // Products table columns
    'table.productName': 'Наименование',
    'table.price': 'Цена',
    'table.turnover': 'Оборач-ть',
    'table.sizeGroup': 'Габаритная группа',
    'table.storagePerDay': 'Хранение сут/сум',
    'table.shop': 'Магазин',
    'table.abcOrders': 'ABC заказы',
    'table.abcProfit': 'ABC прибыль',
    'table.abcRevenue': 'ABC выручка',
    'table.noDataProducts': 'Нет данных. Загрузите left-out-report_old и sells_report.',

    // Report upload
    'report.salesReport': 'Отчет по продажам',
    'report.expensesReport': 'Отчет по услугам',
    'report.storageReport': 'Отчет по хранению',
    'report.inventoryOld': 'Остатки (старый формат)',

    // Expenses
    'expense.date': 'Дата',
    'expense.save': 'Сохранить',
    'expense.add': 'Добавить',
    'expense.type': 'Тип',
    'expense.amount': 'Сумма',
    'expense.actions': 'Действия',
    'expense.loading': 'Загрузка...',
    'expense.noExpensesAdded': 'Нет добавленных расходов',
    'expense.editDesc': 'Измените данные расхода',
    'expense.addDesc': 'Заполните форму для добавления нового расхода',
    'expense.selectDate': 'Выберите дату',

    // Report upload (screenshots)
    'report.uploadButton': 'Загрузить отчеты',
    'report.uploadTitle': 'Загрузка отчетов UZUM',
    'report.howItWorks': 'Как это работает?',
    'report.bullet1': 'Загрузите отчёты XLSX из личного кабинета UZUM',
    'report.bullet2': 'Система автоматически распознает тип отчёта и импортирует данные',
    'report.bullet3': 'ВАЖНО: Все отчёты должны быть за один период',
    'report.dragOrClick': 'Перетащите файл или нажмите',
    'report.close': 'Закрыть',
    'report.upload': 'Загрузить',
    'report.lastUpload': 'Последняя загрузка',
    'report.uploadingReports': 'Загрузка отчётов...',
    'report.importedRows': 'Импортировано: {0} строк',
    'report.onlyLeftout': 'Принимается только left-out-report_old',
    'report.productAdLink': 'Связь товаров с рекламой',
    'report.adLinkDesc': 'Укажите ID рекламных кампаний для точного расчёта затрат на продвижение каждого товара.',
    'report.enterAdId': 'Введите ID рекламы',
    'report.adId': 'ID рекламы',
    'report.loadError': 'Ошибка загрузки данных',
    'shipment.noDataHint': 'Нет данных. Загрузите отчёт «Остатки (старый)» (left-out-report_old) с колонкой Оборачиваемость < 60.',
    'search.byNameArticle': 'Поиск по названию, артикулу...',
    'products.groupByCards': 'Сгруппировать по карточкам',
    'expense.howItWorks': 'Как это работает?',
    'expense.howItWorks1': 'Здесь можно вручную добавить любые дополнительные расходы, которые не передаются по выгрузке в отчетах или через API из маркетплейса',
    'expense.howItWorks2': 'Примеры расходов - самовыкупы, зарплата, внешняя реклама, своя логистика и т.д.',
    'expense.howItWorks3': 'Расходы будут учитываться во всех отчетах с финансами для выбранной даты и магазина/товара (если указаны)',
    'expense.howItWorks4': 'Если не указаны — расходы будут добавлены в месячный отчет в общем',
    'expense.addExpense': 'Добавить расход',
    'expense.editExpense': 'Редактировать расход',
    'expense.typeLabel': 'Тип расхода',
    'expense.selectType': 'Выберите тип',
    'expense.notSelected': 'Не выбран',
    'expense.notSelectedItem': 'Не выбрано',
    'expense.selectShopOptional': 'Выберите магазин (опционально)',
    'expense.selectNameOptional': 'Выберите наименование (опционально)',
    'expense.noShopsAvailable': 'Нет доступных магазинов (загрузите seller-storage)',
    'expense.noNamesAvailable': 'Нет доступных наименований (загрузите left-out-report_old)',
    'expense.commentOptional': 'Добавьте комментарий (опционально)',
    'expense.typeSelfBuy': 'Самовыкуп',
    'expense.typeSalary': 'Зарплата',
    'expense.typeExternalAds': 'Внешняя реклама',
    'expense.typeOwnLogistics': 'Своя логистика',
    'expense.typePackaging': 'Упаковка',
    'expense.typeRent': 'Аренда',
    'expense.typeOther': 'Прочее',
    'shipment.daysUntil': 'Дней до отгрузки',
    'shipment.daysCount': 'Количество дней',
    'shipment.daysDescription': 'Укажите через сколько дней планируется отгрузка товара начиная с даты выгрузки последнего отчета',
    'shipment.considerStock': 'Учитывать остатки на складах',
    'shipment.yes': 'Да',
    'shipment.no': 'Нет',
    'shipment.calculate': 'Рассчитать',
    'shipment.calculating': 'Расчёт…',
    'shipment.recommendations': 'Рекомендации по отгрузке',
    'shipment.exportXLSX': 'Выгрузить в XLSX',
    'shipment.product': 'Товар',
    'shipment.article': 'Артикул',
    'shipment.inStock': 'На складе',
    'shipment.salesPerDay': 'Продаж в день',
    'shipment.recommendedQty': 'Рекомендуемое кол-во',
    'shipment.plannedToShip': 'Запланировано к отгрузке',
    'shipment.exportedRows': 'Выгружено {0} строк',
    'monthly.jan': 'Янв',
    'monthly.feb': 'Фев',
    'monthly.mar': 'Мар',
    'monthly.apr': 'Апр',
    'monthly.may': 'Май',
    'monthly.jun': 'Июн',
    'monthly.jul': 'Июл',
    'monthly.aug': 'Авг',
    'monthly.sep': 'Сен',
    'monthly.oct': 'Окт',
    'monthly.nov': 'Ноя',
    'monthly.dec': 'Дек',

    // Index alerts
    'alert.noStockData': 'Нет данных по складу. Загрузите файл left-out-report_old.',
    'alert.stockZero': 'Склад = 0',
    'alert.stockZeroDesc': 'По данным left-out-report_old на складе 0. Проверь выгрузку «Склад» или фильтр магазина.',
    'alert.stockZeroReasonAll': 'По последней выгрузке склада (left-out-report_old) сумма «В продаже» = 0. Проверь файл склада/остатков.',
    'common.snapshot': 'Срез',
  },
  uz: {
    // Navigation
    'nav.dashboard': 'Boshqaruv paneli',
    'nav.products': 'Mahsulotlar',
    'nav.analytics': 'Tahlil',
    'nav.competitors': 'Raqobatchilar',
    'nav.trends': 'Trendlar',
    'nav.reports': 'Hisobotlar',
    'nav.support': 'Yordam',
    
    // Tabs
    'tabs.summary': 'Xulosa',
    'tabs.products': 'Mahsulotlar',
    'tabs.daily': 'Kunlik',
    'tabs.expenses': 'Xarajatlar',
    'tabs.shipment': 'Yetkazib berish',
    
    // Filters
    'filter.today': 'Bugun',
    'filter.yesterday': 'Kecha',
    'filter.week': 'Hafta',
    'filter.month': 'Oy',
    'filter.year': 'Yil',
    'filter.period': 'Davr',
    'filter.all': 'Hammasi',
    'filter.excess': 'Ortiqcha',
    'filter.outOfStock': 'Omborda yo\'q',
    'filter.needSupply': 'Yetkazish kerak',
    
    // KPI Cards
    'kpi.revenue': 'Daromad',
    'kpi.orders': 'Buyurtmalar',
    'kpi.returns': 'Qaytarishlar',
    'kpi.profit': 'Foyda',
    'kpi.marginality': 'Marjinallik',
    'kpi.averageCheck': "O'rtacha chek",
    
    // Blocks
    'block.finances': 'Moliya',
    'block.expenses': 'Xarajatlar',
    'block.warehouse': 'Ombor',
    'block.revenueProgress': "Jami daromad",
    
    // Finance items
    'finance.revenue': 'Daromad',
    'finance.logistics': 'Logistika',
    'finance.commission': 'Komissiya',
    'finance.promoDiscount': 'Aksiya chegirmasi',
    'finance.netRevenue': 'Sof daromad',
    
    // Expense items
    'expense.soldGoodsCost': "Sotilgan tovarlar tannarxi",
    'expense.logistics': 'Logistika',
    'expense.commission': 'Komissiya',
    'expense.promoDiscount': 'Aksiya chegirmasi',
    'expense.advertising': 'Reklama',
    'expense.fines': 'Jarimalar',
    'expense.storage': 'Saqlash',
    'expense.other': 'Boshqa',
    'expense.total': 'Jami xarajatlar',
    
    // Warehouse items
    'warehouse.warehouseStock': "Ombordagi tovar tannarxi",
    'warehouse.potentialRevenue': 'Potentsial daromad',
    'warehouse.potentialProfit': 'Potentsial foyda',
    
    // Table headers
    'table.product': 'Mahsulot',
    'table.article': 'Artikul',
    'table.category': 'Kategoriya',
    'table.costPrice': 'Tannarx',
    'table.price': 'Narx',
    'table.orders': 'Buyurtmalar',
    'table.returns': 'Qaytarishlar',
    'table.stock': 'Qoldiq',
    'table.availability': 'Mavjudlik',
    'table.revenue': 'Daromad',
    'table.profit': 'Foyda',
    'table.margin': 'Marja',
    
    // Availability status
    'availability.excess': 'Ortiqcha',
    'availability.outOfStock': "Omborda yo'q",
    'availability.needSupply': 'Yetkazish kerak',
    
    // Header
    'header.search': "Mahsulot, kategoriya qidirish...",
    'header.notifications': 'Bildirishnomalar',
    'header.allNotifications': 'Barcha bildirishnomalar',
    'header.help': 'Yordam',
    'header.faq': "Ko'p so'raladigan savollar",
    'header.videoTutorials': 'Video darsliklar',
    'header.support': "Qo'llab-quvvatlash",
    'header.myAccount': 'Mening hisobim',
    'header.profile': 'Profil',
    'header.adminPanel': 'Admin panel',
    'header.tariff': 'Tarif',
    'header.extendTariff': 'Tarifni uzaytirish',
    'header.language': 'Til',
    'header.logout': 'Chiqish',
    
    // Profile dialog
    'profile.title': 'Profil',
    'profile.accountData': "Hisob ma'lumotlari",
    'profile.name': 'Ism',
    'profile.email': 'Email',
    'profile.phone': 'Telefon raqami',
    'profile.save': 'Saqlash',
    'profile.tariffPlan': 'Tarif rejasi',
    'profile.active': 'Faol',
    'profile.validUntil': 'Amal qilish muddati',
    'profile.daysRemaining': 'Qolgan kunlar',
    
    // Language dialog
    'language.title': 'Tilni tanlash',
    'language.russian': 'Ruscha',
    'language.uzbek': "O'zbekcha",
    
    // Report upload
    'report.uploadReports': 'Hisobotlarni yuklash',
    'report.sales': 'Sotuvlar',
    'report.expenses': 'Xarajatlar',
    'report.inventory': 'Qoldiqlar',
    'report.storage': 'Saqlash',
    
    // Actions
    'action.export': 'Eksport',
    'action.import': 'Import',
    'action.apply': "Qo'llash",
    'action.cancel': 'Bekor qilish',
    'action.close': 'Yopish',
    
    // Common
    'common.from': 'dan',
    'common.to': 'gacha',
    'common.total': 'Jami',
    'common.pieces': 'dona',
    'common.sum': "so'm",

    // Summary page
    'summary.pageTitle': 'Mening sotuvlarim',
    'summary.blockSales': 'SOTUVLAR',
    'summary.blockFinances': 'MOLIYA',
    'summary.blockExpenses': 'XARAJATLAR',
    'summary.blockWarehouse': 'OMBOR',
    'summary.blockUzumServices': 'UZUM XIZMATLARI',
    'summary.sales.orders': 'Buyurtmalar',
    'summary.sales.ordersTooltip': 'Tanlangan davr uchun jami buyurtmalar soni.',
    'summary.sales.processing': "Qayta ishlanmoqda",
    'summary.sales.processingTooltip': "To'lov kutilayotgan buyurtmalar.",
    'summary.sales.completed': 'Tasdiqlangan',
    'summary.sales.completedTooltip': "Mijoz olib ketgan va 10 kun o'tgan buyurtmalar.",
    'summary.sales.returns': 'Qaytarishlar',
    'summary.sales.returnsTooltip': "Mijoz qaytagan yoki bekor qilgan buyurtmalar.",
    'summary.sales.returnRate': 'Qaytarish foizi',
    'summary.sales.returnRateTooltip': "Bekor qilingan buyurtmalarning tasdiqlangan buyurtmalarga nisbati, foizda.",
    'summary.sales.averageCheck': "O'rtacha chek",
    'summary.sales.averageCheckTooltip': "Davr uchun o'rtacha buyurtma qiymati.",
    'summary.finance.revenue': 'Daromad',
    'summary.finance.revenueTooltip': 'Tovarlar sotuvidan olingan jami summa.',
    'summary.finance.expenses': 'Xarajatlar',
    'summary.finance.expensesTooltip': '"Xarajatlar" yorlig\'idagi barcha xarajatlar (UZUM xizmatlari kirmaydi).',
    'summary.finance.profit': 'Foyda',
    'summary.finance.profitTooltip': 'Daromad – Xarajatlar.',
    'summary.finance.salesProfitability': 'Sotuv rentabelligi',
    'summary.finance.salesProfitabilityTooltip': '(Foyda / Daromad) × 100. Daromadning qaysi qismi foyda ekanini ko\'rsatadi.',
    'summary.finance.roi': 'Investitsiya o\'zini oqlashi',
    'summary.finance.roiTooltip': '(Foyda / tovarlar tannarxi) × 100. Pul qo\'yilmalarning qanchalik foydali ekanini ko\'rsatadi.',
    'summary.finance.revenueTrend': 'Daromad trendi',
    'summary.finance.revenueTrendTooltip': 'Tanlangan joriy davr daromadining oldingi o\'xshash davr daromadi bilan solishtiruvi.',
    'summary.finance.lostRevenue': 'Yo\'qotilgan daromad',
    'summary.finance.lostRevenueTooltip': 'Omborda tovar yo\'qligi tufayli davr uchun potentsial daromad yo\'qotishi = (tovarsiz kunlar) × (kunlik o\'rtacha daromad) barcha tovarlar uchun.',
    'summary.expense.commissionUzum': 'UZUM komissiyasi',
    'summary.expense.logisticsUzum': 'UZUM logistikasi',
    'summary.expense.productCost': 'Tovar tannarxi',
    'summary.expense.taxes': 'Soliqlar',
    'summary.expense.extraExpenses': 'Qo\'shimcha xarajatlar',
    'summary.expense.extraExpensesTooltip': '"Qo\'shimcha xarajatlar" yorlig\'ida ko\'rsatilgan xarajatlar.',
    'summary.uzum.storage': 'UZUM saqlash',
    'summary.uzum.storageTooltip': 'Tanlangan davr uchun tovarlarni saqlash uchun to\'lov.',
    'summary.uzum.ads': 'UZUM reklama',
    'summary.uzum.adsTooltip': 'Tanlangan davr uchun marketing kampaniyalari (BUST topda) qiymati.',
    'summary.uzum.fines': 'UZUM jarimalar',
    'summary.uzum.finesTooltip': 'Tanlangan davr uchun undirilgan jarimalar.',
    'summary.warehouse.stock': 'Ombordagi tovarlar',
    'summary.warehouse.stockTooltip': 'UZUM omborida FBO bo\'yicha sotuv uchun saqlanayotgan tovarlar soni.',
    'summary.warehouse.cost': 'Tovar tannarxi',
    'summary.warehouse.retailPrice': 'Chakana narx',
    'summary.warehouse.retailPriceTooltip': 'UZUM omboridagi tovarlarning bozor narxlari bo\'yicha sotilgandagi qiymati.',
    'filter.allStores': 'Barcha do\'konlar',
    'filter.quickPeriod': 'Tezkor davr',
    'filter.from': 'Dan',
    'filter.to': 'Gacha',
    'filter.apply': 'Qo\'llash',
    'filter.reset': 'Tozalash',
    'filter.viewDay': 'Kunlik',
    'filter.viewWeek': 'Haftalik',
    'filter.viewMonth': 'Oylik',
    'filter.noSellsData': 'sells-report ma\'lumotlari yo\'q',
    'filter.dateErrorOrder': '"Dan" sanasi "Gacha"dan keyin bo\'lishi mumkin emas',
    'filter.dateErrorRange': 'Ma\'lumotlar oralig\'ida sanalarni tanlang',
    'tabs.expensesExtra': "Qo'shimcha xarajatlar",
    'tabs.shipmentLabel': 'Yuklash',
    'tabs.monthly': 'Oylik',
    'chart.salesByDay': 'Kunlik sotuvlar',
    'chart.noData': 'Ma\'lumot yo\'q',
    'header.loggedOut': 'Tizimdan chiqdingiz',
    'header.seller': 'Sotuvchi',
    'header.settings': 'Sozlamalar',
    'header.tariffs': 'Tariflar',

    'chart.ordersPcs': 'Buyurtmalar, dona',
    'chart.revenueMlnSum': 'Daromad, mln so\'m',
    'chart.addComment': 'Izoh qo\'shish',
    'chart.date': 'Sana',
    'chart.selectDate': 'Sanani tanlang',
    'chart.comment': 'Izoh',
    'chart.done': 'Tayyor',
    'chart.delete': 'O\'chirish',
    'chart.reallyOrders': 'haqiqiy',
    'chart.costsThousandSum': "Xarajatlar, ming so'm",
    'progress.mln': 'mln',
    'progress.billion': 'mlrd',
    'progress.thousand': 'ming',

    'product.products': 'Mahsulotlar',
    'product.productTitle': 'MAHSULOT',
    'product.name': 'Nomi',
    'product.productType': 'Mahsulot turi',
    'product.productId': 'Mahsulot ID',
    'product.comment': 'Izoh',
    'product.commentPlaceholder': 'Mahsulotga izoh qoldiring...',
    'product.saving': 'Saqlanmoqda...',
    'product.save': 'Saqlash',
    'product.saveCommentError': 'Izohni saqlashda xato: {0}',
    'product.params': 'Mahsulot parametrlari',
    'product.orders': 'Buyurtmalar',
    'product.stock': 'Qoldiqlar',
    'product.sizeGroup': 'Gabarit guruhi',
    'product.barcode': 'Shtrixkod',
    'product.storage': 'Saqlash',
    'product.storageDaySum': 'kun/so\'m',
    'product.total': 'Jami',
    'product.noVariants': 'Mahsulot variantlari yo\'q',
    'product.marginality': 'Marjinallik',
    'product.revenueShare': 'Jami daromaddan',
    'product.selectPeriod': 'Sana filtrida davrni tanlang',

    'daily.chartTitle': 'Buyurtmalar va sotuvlar grafigi',
    'daily.dataByDay': 'Kunlik ma\'lumotlar',
    'daily.loading': 'Yuklanmoqda...',
    'daily.loadError': 'Ma\'lumotlarni yuklashda xato',
    'daily.noDataPeriod': 'Tanlangan davr uchun ma\'lumot yo\'q',
    'daily.date': 'Sana',
    'daily.orders': 'Buyurtmalar',
    'daily.buys': 'Tasdiqlangan',
    'daily.returns': 'Qaytarishlar',
    'daily.revenue': 'Daromad',
    'daily.commission': 'Komissiya',
    'daily.logistics': 'Logistika',
    'daily.storage': 'Saqlash',
    'daily.ads': 'Reklama',
    'daily.penalties': 'Jarimalar',
    'daily.cogs': 'Tannarx',
    'daily.tax': 'Soliq',
    'daily.profitNet': 'Sof foyda',
    'daily.granularityDay': 'Kun',
    'daily.granularityWeek': 'Hafta',
    'daily.granularityMonth': 'Oy',

    'monthly.totalSold': 'Jami sotilgan',
    'monthly.revenue': 'Daromad',
    'monthly.cost': 'Tannarx',
    'monthly.commission': 'Komissiya',
    'monthly.logistics': 'Logistika',
    'monthly.storage': 'Saqlash',
    'monthly.ads': 'Reklama',
    'monthly.fines': 'Jarimalar',
    'monthly.tax': 'Soliq',
    'monthly.extraExpenses': 'Qo\'shimcha xarajatlar',
    'monthly.netProfit': 'SOF FOYDA',
    'monthly.title': 'Oylik moliyaviy ko\'rsatkichlar',
    'monthly.year': 'yil',
    'monthly.indicator': 'Ko\'rsatkich',

    'table.productName': 'Nomi',
    'table.price': 'Narx',
    'table.turnover': 'Aylanma',
    'table.sizeGroup': 'Gabarit guruhi',
    'table.storagePerDay': 'Saqlash kun/so\'m',
    'table.shop': 'Do\'kon',
    'table.abcOrders': 'ABC buyurtmalar',
    'table.abcProfit': 'ABC foyda',
    'table.abcRevenue': 'ABC daromad',
    'table.noDataProducts': 'Ma\'lumot yo\'q. left-out-report_old va sells_report yuklang.',

    'report.salesReport': 'Sotuvlar hisoboti',
    'report.expensesReport': 'Xizmatlar hisoboti',
    'report.storageReport': 'Saqlash hisoboti',
    'report.inventoryOld': 'Qoldiqlar (eski format)',

    'expense.date': 'Sana',
    'expense.save': 'Saqlash',
    'expense.add': 'Qo\'shish',
    'expense.type': 'Turi',
    'expense.amount': 'Summa',
    'expense.actions': 'Amallar',
    'expense.loading': 'Yuklanmoqda...',
    'expense.noExpensesAdded': 'Qo\'shilgan xarajatlar yo\'q',
    'expense.editDesc': 'Xarajat ma\'lumotlarini o\'zgartiring',
    'expense.addDesc': 'Yangi xarajat qo\'shish uchun formani to\'ldiring',
    'expense.selectDate': 'Sanani tanlang',

    'report.uploadButton': 'Hisobotlarni yuklash',
    'report.uploadTitle': 'UZUM hisobotlarini yuklash',
    'report.howItWorks': 'Qanday ishlaydi?',
    'report.bullet1': 'UZUM shaxsiy kabinetidan XLSX hisobotlarni yuklang',
    'report.bullet2': 'Tizim hisobot turini avtomatik aniqlaydi va ma\'lumotlarni import qiladi',
    'report.bullet3': 'MUHIM: Barcha hisobotlar bir davr uchun bo\'lishi kerak',
    'report.dragOrClick': 'Faylni torting yoki bosing',
    'report.close': 'Yopish',
    'report.upload': 'Yuklash',
    'report.lastUpload': 'Oxirgi yuklash',
    'report.uploadingReports': 'Hisobotlar yuklanmoqda...',
    'report.importedRows': 'Import qilindi: {0} qator',
    'report.onlyLeftout': 'Faqat left-out-report_old qabul qilinadi',
    'report.productAdLink': 'Mahsulotlar va reklama aloqasi',
    'report.adLinkDesc': 'Har bir mahsulotni reklama xarajatlarini aniq hisoblash uchun reklama kampaniyalari ID sini kiriting.',
    'report.enterAdId': 'Reklama ID sini kiriting',
    'report.adId': 'Reklama ID',
    'report.loadError': 'Ma\'lumotlarni yuklashda xato',
    'shipment.noDataHint': 'Ma\'lumot yo\'q. «Qoldiqlar (eski)» hisobotini (left-out-report_old) Aylanma < 60 ustuni bilan yuklang.',
    'search.byNameArticle': 'Nomi, artikuli bo\'yicha qidiruv...',
    'products.groupByCards': 'Kartochkalar bo\'yicha guruhlash',
    'expense.howItWorks': 'Qanday ishlaydi?',
    'expense.howItWorks1': 'Bu yerda hisobotlar yoki API orqali uzatilmaydigan qo\'shimcha xarajatlarni qo\'lda qo\'shishingiz mumkin',
    'expense.howItWorks2': 'Misol: o\'zini o\'zi xarid qilish, maosh, tashqi reklama, o\'z logistikasi va boshqalar',
    'expense.howItWorks3': 'Xarajatlar tanlangan sana va do\'kon/mahsulot uchun barcha moliyaviy hisobotlarda hisobga olinadi',
    'expense.howItWorks4': 'Ko\'rsatilmasa — xarajatlar oylik hisobotga umuman qo\'shiladi',
    'expense.addExpense': 'Xarajat qo\'shish',
    'expense.editExpense': 'Xarajatni tahrirlash',
    'expense.typeLabel': 'Xarajat turi',
    'expense.selectType': 'Turni tanlang',
    'expense.notSelected': 'Tanlanmagan',
    'expense.notSelectedItem': 'Tanlanmagan',
    'expense.selectShopOptional': 'Do\'konni tanlang (ixtiyoriy)',
    'expense.selectNameOptional': 'Nomini tanlang (ixtiyoriy)',
    'expense.noShopsAvailable': 'Do\'konlar mavjud emas (seller-storage yuklang)',
    'expense.noNamesAvailable': 'Nomlar mavjud emas (left-out-report_old yuklang)',
    'expense.commentOptional': 'Izoh qo\'shing (ixtiyoriy)',
    'expense.typeSelfBuy': 'O\'zini o\'zi xarid',
    'expense.typeSalary': 'Maosh',
    'expense.typeExternalAds': 'Tashqi reklama',
    'expense.typeOwnLogistics': 'O\'z logistikasi',
    'expense.typePackaging': 'Qadoqlash',
    'expense.typeRent': 'Ijara',
    'expense.typeOther': 'Boshqa',
    'shipment.daysUntil': 'Yuklashgacha kunlar',
    'shipment.daysCount': 'Kunlar soni',
    'shipment.daysDescription': 'Oxirgi hisobot yuklash sanasidan boshlab tovar yuklanishi rejalashtirilgan kunlar sonini kiriting',
    'shipment.considerStock': 'Ombor qoldiqlarini hisobga olish',
    'shipment.yes': 'Ha',
    'shipment.no': 'Yo\'q',
    'shipment.calculate': 'Hisoblash',
    'shipment.calculating': 'Hisoblanmoqda…',
    'shipment.recommendations': 'Yuklash bo\'yicha tavsiyalar',
    'shipment.exportXLSX': 'XLSX ga yuklash',
    'shipment.product': 'Mahsulot',
    'shipment.article': 'Artikul',
    'shipment.inStock': 'Omborda',
    'shipment.salesPerDay': 'Kunlik sotuv',
    'shipment.recommendedQty': 'Tavsiya etilgan miqdor',
    'shipment.plannedToShip': 'Yuklashga rejalashtirilgan',
    'shipment.exportedRows': '{0} qator yuklandi',
    'monthly.jan': 'Yan',
    'monthly.feb': 'Fev',
    'monthly.mar': 'Mar',
    'monthly.apr': 'Apr',
    'monthly.may': 'May',
    'monthly.jun': 'Iyun',
    'monthly.jul': 'Iyul',
    'monthly.aug': 'Avg',
    'monthly.sep': 'Sen',
    'monthly.oct': 'Okt',
    'monthly.nov': 'Noy',
    'monthly.dec': 'Dek',

    'alert.noStockData': 'Ombor ma\'lumotlari yo\'q. left-out-report_old faylini yuklang.',
    'alert.stockZero': 'Ombor = 0',
    'alert.stockZeroDesc': 'left-out-report_old ma\'lumotlariga ko\'ra omborda 0. «Ombor» yuklash yoki do\'kon filtrini tekshiring.',
    'alert.stockZeroReasonAll': 'Oxirgi ombor yuklashida (left-out-report_old) «Sotuvda» summa = 0. Ombor/qoldiq faylini tekshiring.',
    'common.snapshot': 'Kesim',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
