# Export all schemas for backward compatibility
from . import auth
from .shops import Shop, ShopsResponse
from .common import PeriodInfo, Filters, Paging
from .charts import (
    RevenuePoint,
    RevenueFilters,
    RevenueDailyResponse,
    StockItem,
    StockFilters,
    StockCurrentResponse,
    ChartPoint,
    ChartRevenueDailyResponse,
    ChartStockCurrentResponse,
    StockDailyPoint,
    StockDailyFilters,
    StockDailyResponse,
    UzumServicesPoint,
    UzumServicesFilters,
    UzumServicesDailyResponse,
    OrdersSalesDailyPoint,
    OrdersSalesDailyFilters,
    OrdersSalesDailyResponse,
    DailySummaryPoint,
    DailySummaryFilters,
    DailySummaryResponse,
    ShipmentRecommendationItem,
    ShipmentRecommendationsResponse,
    ProductsTableItem,
    ProductsTableResponse,
    ProductCardAllTimeMetrics,
    ExpensesKpiMetric,
    ExpensesSummary,
    ExpensesServiceItem,
    ExpensesWeekPart,
    ExpensesWeekPoint,
    ExpensesBreakdownFilters,
    ExpensesBreakdownResponse,
)
from .products import ProductItem, ProductsResponse
from .kpi import KPISummaryResponse, CumulativeRevenueResponse

__all__ = [
    "auth",
    "Shop",
    "ShopsResponse",
    "PeriodInfo",
    "Filters",
    "Paging",
    "RevenuePoint",
    "RevenueFilters",
    "RevenueDailyResponse",
    "StockItem",
    "StockFilters",
    "StockCurrentResponse",
    "ChartPoint",
    "ChartRevenueDailyResponse",
    "ChartStockCurrentResponse",
    "StockDailyPoint",
    "StockDailyFilters",
    "StockDailyResponse",
    "UzumServicesPoint",
    "UzumServicesFilters",
    "UzumServicesDailyResponse",
    "OrdersSalesDailyPoint",
    "OrdersSalesDailyFilters",
    "OrdersSalesDailyResponse",
    "DailySummaryPoint",
    "DailySummaryFilters",
    "DailySummaryResponse",
    "ShipmentRecommendationItem",
    "ShipmentRecommendationsResponse",
    "ProductsTableItem",
    "ProductsTableResponse",
    "ProductCardAllTimeMetrics",
    "ExpensesKpiMetric",
    "ExpensesSummary",
    "ExpensesServiceItem",
    "ExpensesWeekPart",
    "ExpensesWeekPoint",
    "ExpensesBreakdownFilters",
    "ExpensesBreakdownResponse",
    "ProductItem",
    "ProductsResponse",
    "KPISummaryResponse",
    "CumulativeRevenueResponse",
]
